#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from pathlib import Path

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from introduction.vcdTool.apis import RunRequest
    from introduction.vcdTool.app import VCDApp
else:
    from .apis import RunRequest
    from .app import VCDApp


_PACKAGE = "introduction.vcdTool"
_PROJECT = "digital-control - introduction.vcdTool"
_AUTHOR = "digital-control"
_REQUIRED_MODULES = [
    "introduction.vcdTool.cli",
    "introduction.vcdTool.apis",
    "introduction.vcdTool.app",
]
_OPTIONAL_MODULES = [
    "introduction.vcdTool.core",
    "introduction.vcdTool.design",
    "introduction.vcdTool.io",
    "introduction.vcdTool.utils",
    "introduction.vcdTool.plotting",
]


def _available_modules() -> list[str]:
    """Return required modules plus optional modules that Python can import."""
    modules = list(_REQUIRED_MODULES)
    for mod in _OPTIONAL_MODULES:
        if importlib.util.find_spec(mod) is not None:
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text unless the file exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support folders and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> vcdTool -> introduction -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build a Sphinx index page with safe heading lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that documents only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _available_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def parse_decode_list(s: str | None) -> list[tuple[str, int]]:
    """Parse a comma-separated decode list such as ``code:10,bus:8``."""
    out: list[tuple[str, int]] = []
    if not s:
        return out
    for item in s.split(","):
        item = item.strip()
        if not item:
            continue
        if ":" not in item:
            print(f"[warn] ignoring decode {item!r} (use name:nbits)", file=sys.stderr)
            continue
        name, n = item.split(":", 1)
        name = name.strip()
        try:
            nbits = int(n)
            assert nbits > 0
        except Exception:
            print(f"[warn] ignoring decode {item!r} (nbits must be positive int)", file=sys.stderr)
            continue
        if not name:
            print(f"[warn] ignoring decode {item!r} (name is empty)", file=sys.stderr)
            continue
        out.append((name, nbits))
    return out


def _add_run_arguments(ap: argparse.ArgumentParser) -> None:
    """Add the original vcdTool run arguments to a parser."""
    ap.add_argument("vcd", help="input VCD file (relative to --in-dir by default)")
    ap.add_argument("--signals", help="comma-separated signal names to plot (default: first 8)")
    ap.add_argument(
        "--units",
        choices=["s", "ms", "us", "ns"],
        default="us",
        help="x-axis units (default: us)",
    )
    ap.add_argument(
        "--backend",
        choices=["mpl", "plotly"],
        default="mpl",
        help="which plot backend to use (default: mpl)",
    )
    ap.add_argument(
        "--overlay",
        action="store_true",
        help="(plotly) overlay signals on one axis instead of stacked subplots",
    )
    ap.add_argument("--out-csv", dest="out_csv", help="optional CSV export of the traces")
    ap.add_argument(
        "--csv-units",
        choices=["s", "ms", "us", "ns"],
        default="s",
        help="time units for CSV (default: s)",
    )
    ap.add_argument("--png", help="save Matplotlib figure to PNG (mpl backend)")
    ap.add_argument("--html", help="save Plotly figure to HTML (plotly backend)")
    ap.add_argument("--decode", help="split buses into bits, e.g. --decode 'code:10,bus:8'")
    ap.add_argument(
        "--in-dir",
        default="in",
        help="default input directory for relative VCD (default: in)",
    )
    ap.add_argument(
        "--out-dir",
        default="out",
        help="default output directory for relative files (default: out)",
    )


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog=_PACKAGE,
        description="Plot VCD signals with Matplotlib or Plotly.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="plot or export VCD signal traces",
        description="Run the vcdTool manifest/plot/export workflow.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_vcd(args: argparse.Namespace) -> int:
    """Run the VCD plotting/export workflow."""
    req = RunRequest(
        vcd=args.vcd,
        signals=[s.strip() for s in args.signals.split(",")] if args.signals else None,
        units=args.units,
        backend=args.backend,
        overlay=args.overlay,
        out_csv=args.out_csv,
        csv_units=args.csv_units,
        png=args.png,
        html=args.html,
        decode=parse_decode_list(args.decode),
        in_dir=args.in_dir,
        out_dir=args.out_dir,
    )

    app = VCDApp()
    res = app.run(req)

    print("\n=== vcdTool manifest ===")
    print(f"VCD: {res['vcd']}")
    print(f"Signals: {', '.join(res['signals'])}")
    outs = res["out"]
    print(f"PNG:  {outs.get('png')}")
    print(f"HTML: {outs.get('html')}")
    print(f"CSV:  {outs.get('csv')}\n")
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the vcdTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_vcd(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
