#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`pole_placement.controllabilityTool`.

The CLI supports two usage styles:

1. Modern subcommand form::

       python -m pole_placement.controllabilityTool.cli run --json in/system.json --pretty

2. Historical no-subcommand form::

       python -m pole_placement.controllabilityTool.cli --json in/system.json --pretty

It also includes a small ``sphinx-skel`` helper for generating a conservative,
GitHub Pages friendly Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from pole_placement.controllabilityTool.apis import RunRequest
    from pole_placement.controllabilityTool.app import ControllabilityApp
else:
    from .apis import RunRequest
    from .app import ControllabilityApp


_PACKAGE = "pole_placement.controllabilityTool"
_PROJECT = "Digital Control - pole_placement.controllabilityTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "pole_placement.controllabilityTool.cli",
    "pole_placement.controllabilityTool.apis",
]

_OPTIONAL_MODULES = [
    "pole_placement.controllabilityTool.app",
    "pole_placement.controllabilityTool.core",
    "pole_placement.controllabilityTool.io",
    "pole_placement.controllabilityTool.utils",
    "pole_placement.controllabilityTool.plotting",
    "pole_placement.controllabilityTool.design",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "scipy",
    "scipy.linalg",
    "scipy.integrate",
    "sympy",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module still fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper performs the stricter
    check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> controllabilityTool -> pole_placement -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(p: argparse.ArgumentParser) -> None:
    """Add controllability analysis arguments to ``p``."""
    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument("--json", type=str, help="Path to JSON system file, usually under in/.")
    src.add_argument("--A", type=str, help='A matrix string, e.g. "0 1; -2 -3".')

    p.add_argument("--B", type=str, help='B matrix string, e.g. "0; 1" (required if not using --json).')
    p.add_argument("--C", type=str, help="C matrix string, needed for --output-ctrb.")
    p.add_argument("--D", type=str, help="D matrix string, optional for --output-ctrb.")

    p.add_argument("--discrete", action="store_true", help="Treat system as discrete-time.")
    p.add_argument("--horizon", type=int, default=None, help="Controllability/output horizon. Default is n.")
    p.add_argument("--tol", type=float, default=None, help="Numeric rank tolerance for SVD-based rank checks.")

    # State tests
    p.add_argument("--pbh", action="store_true", help="Run PBH controllability test.")
    p.add_argument("--gram", action="store_true", help="Compute infinite-horizon controllability Gramian if stable.")
    p.add_argument("--finite-dt", type=int, default=None, help="Compute finite-horizon discrete-time Gramian over N steps.")
    p.add_argument("--finite-ct", type=float, default=None, help="Compute finite-horizon continuous-time Gramian over T seconds.")
    p.add_argument("--minreal", action="store_true", help="Trim uncontrollable modes and write *_minreal.json.")
    p.add_argument("--symbolic", action="store_true", help="Run SymPy exact-rank test on the controllability matrix.")

    # Output controllability
    p.add_argument("--output-ctrb", action="store_true", help="Run output controllability rank test. Needs C, optional D.")
    p.add_argument("--save-output-csv", action="store_true", help="Save output controllability matrix to out/.")

    # Output files / printing
    p.add_argument("--pretty", action="store_true", help="Pretty-print matrices and results.")
    p.add_argument("--name", type=str, default="ctrb", help="Base name for output files.")
    p.add_argument("--save-csv", action="store_true", help="Save controllability matrix CSV to out/.")
    p.add_argument("--save-json", action="store_true", help="Save JSON summary to out/.")
    p.add_argument("--save-gram", action="store_true", help="Save any computed Gramian to CSV.")
    p.add_argument("--report", type=str, default=None, help="Optional text report path, e.g. out/ctrb_report.txt.")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="pole_placement.controllabilityTool",
        description=(
            "Ogata-grade controllability toolbox for continuous-time and "
            "discrete-time systems: state controllability, output "
            "controllability, PBH tests, Gramians, symbolic rank, and minreal."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run controllability analysis",
        description=(
            "Run state/output controllability checks, PBH tests, Gramian "
            "analysis, symbolic rank checks, or uncontrollable-mode trimming."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_controllability(ns: argparse.Namespace) -> int:
    """Run the controllability analysis workflow."""
    req = RunRequest(
        json_path=ns.json,
        A=ns.A,
        B=ns.B,
        C=ns.C,
        D=ns.D,
        discrete=ns.discrete,
        horizon=ns.horizon,
        tol=ns.tol,
        pbh=ns.pbh,
        gram=ns.gram,
        finite_dt=ns.finite_dt,
        finite_ct=ns.finite_ct,
        minreal=ns.minreal,
        symbolic=ns.symbolic,
        output_ctrb=ns.output_ctrb,
        save_output_csv=ns.save_output_csv,
        pretty=ns.pretty,
        name=ns.name,
        save_csv=ns.save_csv,
        save_json=ns.save_json,
        save_gram=ns.save_gram,
        report=ns.report,
    )

    app = ControllabilityApp()
    res = app.run(req)
    return int(getattr(res, "exit_code", 0))


def _run_sphinx_skel(ns: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(ns.dest, force=ns.force)

    print(f"Sphinx skeleton ready: {ns.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {ns.dest / '_static' / '.gitkeep'}")
    print(f"  {ns.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the controllabilityTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_controllability(args)

    parser.print_help()
    return 0


# Backward-compatible alias for older imports/tests that used build_arg_parser.
build_arg_parser = build_parser


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
