#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Command-line interface for :mod:`introduction.demuxTool`.

The CLI preserves the original demultiplexer workflow while adding a small,
conservative Sphinx skeleton generator for GitHub Pages deployments.
"""
from __future__ import annotations

import argparse
import importlib
import os
import sys
from pathlib import Path

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from introduction.demuxTool.apis import RunRequest
    from introduction.demuxTool.app import DemuxApp
else:
    from .apis import RunRequest
    from .app import DemuxApp


_PACKAGE = "introduction.demuxTool"
_PROJECT = "Digital Control - introduction.demuxTool"
_AUTHOR = "Digital Control"
_REQUIRED_MODULES = [
    "introduction.demuxTool.cli",
    "introduction.demuxTool.apis",
    "introduction.demuxTool.app",
]
_OPTIONAL_MODULES = [
    "introduction.demuxTool.core",
    "introduction.demuxTool.io",
    "introduction.demuxTool.utils",
    "introduction.demuxTool.design",
    "introduction.demuxTool.plotting",
]
_COMMANDS = {"run", "sphinx-skel", "-h", "--help"}


def _module_importable(modname: str) -> bool:
    """Return ``True`` only when a module can be imported by Sphinx.

    ``importlib.util.find_spec()`` is not enough for autodoc safety because it
    only checks that a module exists; it does not execute the module body. The
    deploy failure happened because autodoc found modules that later failed at
    import time. This helper performs the actual import and treats failures as a
    signal to omit the module from generated ``api.rst``.
    """
    try:
        importlib.import_module(modname)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that Python can actually import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text unless the file exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support folders and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> demuxTool -> introduction -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = ["pyrtl", "graphviz"]
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build a Sphinx index page with safe heading lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that documents only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _available_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(ap: argparse.ArgumentParser) -> None:
    """Add the demux simulation arguments to a parser."""
    ap.add_argument("--csv", help="Input CSV with columns: sel,x.")
    ap.add_argument(
        "--json",
        dest="json_spec",
        help='Input JSON file/inline list, or object such as {"vectors":[...]}.',
    )
    ap.add_argument("--out", help="Optional CSV to write outputs.")
    ap.add_argument(
        "--n",
        type=int,
        default=4,
        help="Number of demultiplexer outputs. Default: 4.",
    )
    ap.add_argument(
        "--bits",
        type=int,
        default=8,
        help="Input data bitwidth. Default: 8.",
    )
    ap.add_argument(
        "--trace",
        help="Optional VCD output filename, for example demux.vcd.",
    )
    ap.add_argument(
        "--strict",
        action="store_true",
        help="Guard sel in [0..N-1]; invalid selections drive all outputs to zero.",
    )
    ap.add_argument(
        "--in-dir",
        default="in",
        help="Default input directory for relative paths. Default: in.",
    )
    ap.add_argument(
        "--out-dir",
        default="out",
        help="Default output directory for relative paths. Default: out.",
    )


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="introduction.demuxTool",
        description="N-way demultiplexer simulator with CSV/JSON vectors and optional VCD output.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run demux simulation",
        description="Run an N-way demultiplexer simulation from CSV or JSON vectors.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing Sphinx skeleton files.",
    )

    return parser


def _run_demux(args: argparse.Namespace) -> int:
    """Run the demultiplexer workflow."""
    if not args.csv and not args.json_spec:
        raise ValueError("provide --csv or --json")

    req = RunRequest(
        n_outputs=args.n,
        data_bw=args.bits,
        strict=args.strict,
        csv_path=args.csv,
        json_spec=args.json_spec,
        out_csv=args.out,
        out_vcd=args.trace,
        in_dir=args.in_dir,
        out_dir=args.out_dir,
    )

    app = DemuxApp()
    res = app.run(req)

    for r in res.rows:
        outs = " ".join([f"y{k}={r[f'y{k}']}" for k in range(res.n_outputs)])
        print(f"[{r['cycle']}] sel={r['sel']} x={r['x']} => {outs}")

    if res.out_csv:
        print(f"Wrote results CSV to {res.out_csv}")
    if res.out_vcd:
        print(f"Wrote VCD wavefile to {res.out_vcd}")
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def _normalize_legacy_argv(argv: list[str]) -> list[str]:
    """Preserve historical no-subcommand usage by inserting ``run``.

    Examples
    --------
    ``python cli.py --json '[...]'`` becomes ``python cli.py run --json '[...]'``.
    """
    if not argv:
        return argv
    if argv[0] in _COMMANDS:
        return argv
    return ["run", *argv]


def main(argv: list[str] | None = None) -> int:
    """Run the demuxTool command-line interface."""
    raw_args = list(sys.argv[1:] if argv is None else argv)
    parser = build_parser()
    args = parser.parse_args(_normalize_legacy_argv(raw_args))

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd == "run":
        try:
            return _run_demux(args)
        except ValueError as exc:
            parser.error(str(exc))
            return 2

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
