#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`system_design.zGridTool`.

The CLI preserves the original z-grid workflow while adding a ``sphinx-skel``
helper for generating conservative, GitHub Pages friendly Sphinx documentation
files.

Supported execution styles
--------------------------

* ``python -m system_design.zGridTool.cli --T 0.1``
* ``python -m system_design.zGridTool.cli run --T 0.1``
* ``python system_design/zGridTool/cli.py --T 0.1``
* ``python -m system_design.zGridTool.cli sphinx-skel system_design/zGridTool/docs``
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from system_design.zGridTool.apis import RunRequest
    from system_design.zGridTool.app import ZGridApp
    from system_design.zGridTool.io import parse_num_list
else:
    # Normal package execution.
    from .apis import RunRequest
    from .app import ZGridApp
    from .io import parse_num_list


_PACKAGE = "system_design.zGridTool"
_PROJECT = "Digital Control - system_design.zGridTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "system_design.zGridTool.cli",
    "system_design.zGridTool.apis",
]

_OPTIONAL_MODULES = [
    "system_design.zGridTool.app",
    "system_design.zGridTool.core",
    "system_design.zGridTool.io",
    "system_design.zGridTool.utils",
    "system_design.zGridTool.design",
    "system_design.zGridTool.plotting",
    "system_design.zGridTool.examples",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "scipy",
    "scipy.linalg",
    "scipy.signal",
    "sympy",
]


# -----------------------------------------------------------------------------
# Sphinx skeleton helpers
# -----------------------------------------------------------------------------


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module fails during import because an optional dependency is missing. Sphinx
    autodoc needs importable modules, so this helper performs the stricter check
    used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> zGridTool -> system_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


# -----------------------------------------------------------------------------
# Original zGridTool workflow
# -----------------------------------------------------------------------------


def _add_run_arguments(p: argparse.ArgumentParser) -> None:
    """Add the original zGridTool arguments to ``p``."""
    gT = p.add_mutually_exclusive_group(required=True)
    gT.add_argument("--T", type=float, help="Sampling period [s]")
    gT.add_argument("--fs", type=float, help="Sampling frequency [Hz] (overrides T=1/fs)")

    p.add_argument("--zetas", nargs="+", default=["0.1", "0.2", "0.3", "0.4", "0.6", "0.8"])
    p.add_argument("--wd_over_ws", nargs="+", default=["0", "0.1", "0.2", "0.25", "0.3", "0.4", "0.5"])
    p.add_argument("--wnT", nargs="+", default=["0.5", "1.0", "1.5", "2.0"])
    p.add_argument("--theta_max", type=float, default=3.141592653589793)
    p.add_argument("--settling_sigma", type=float, default=None)

    p.add_argument("--pz", nargs="*", default=[])

    p.add_argument("--backend", choices=("mpl", "plotly"), default="mpl")
    p.add_argument("--png", default="zgrid.png")
    p.add_argument("--plotly", dest="plotly_html", default=None)
    p.add_argument("--width", type=int, default=900)
    p.add_argument("--height", type=int, default=900)
    p.add_argument("--dpi", type=int, default=150)
    p.add_argument("--dark", action="store_true")
    p.add_argument("--theme", choices=("plotly_white", "plotly_dark", "plotly"), default="plotly_white")
    p.add_argument("--legend_mode", choices=("minimal", "full"), default="minimal")
    p.add_argument("--legend_loc", choices=("bottom", "top", "right", "inside"), default="bottom")
    p.add_argument("--title", default="z-plane design grid")
    p.add_argument("--title_mode", choices=("auto", "minimal", "full"), default="auto")
    p.add_argument("--responsive", dest="responsive", action="store_true")
    p.add_argument("--fixed_size", dest="responsive", action="store_false")
    p.set_defaults(responsive=True)

    p.add_argument("--export_csv_prefix", default=None)
    p.add_argument("--verbose", action="store_true")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="system_design.zGridTool",
        description="z-grid tool (OOP) with Matplotlib/Plotly backends and Sphinx docs helper.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="generate a z-plane design grid",
        description="Generate a z-plane design grid with MPL or Plotly backends.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_zgrid(args: argparse.Namespace) -> int:
    """Run the z-grid generation workflow."""
    req = RunRequest(
        T=args.T,
        fs=args.fs,
        zetas=parse_num_list(args.zetas),
        wd_over_ws=parse_num_list(args.wd_over_ws),
        wnT=parse_num_list(args.wnT),
        theta_max=float(args.theta_max),
        settling_sigma=args.settling_sigma,
        pz_files=args.pz,
        backend=args.backend,
        png=args.png,
        plotly_html=args.plotly_html,
        width=args.width,
        height=args.height,
        dpi=args.dpi,
        dark=args.dark,
        theme=args.theme,
        legend_mode=args.legend_mode,
        legend_loc=args.legend_loc,
        title=args.title,
        title_mode=args.title_mode,
        responsive=bool(args.responsive),
        export_csv_prefix=args.export_csv_prefix,
        verbose=args.verbose,
    )
    app = ZGridApp()
    res = app.run(req)
    if res.png_path:
        print(f"PNG: {res.png_path}")
    if res.html_path:
        print(f"HTML: {res.html_path}")
    if res.csv_prefix:
        print(f"CSV prefix: {res.csv_prefix}")
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)

    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the zGridTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_zgrid(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
