#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`rst_controllers.rstPlotTool`.

The CLI supports two usage styles:

1. Modern subcommand form::

       python -m rst_controllers.rstPlotTool.cli run out/*.csv --overlay

2. Historical no-subcommand form::

       python -m rst_controllers.rstPlotTool.cli out/*.csv --overlay

It also includes a ``sphinx-skel`` helper for generating a conservative,
GitHub Pages friendly Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from rst_controllers.rstPlotTool.apis import OverlayFilters, RunRequest, YLimits
    from rst_controllers.rstPlotTool.app import RSTPlotApp
else:
    from .apis import OverlayFilters, RunRequest, YLimits
    from .app import RSTPlotApp


_PACKAGE = "rst_controllers.rstPlotTool"
_PROJECT = "Digital Control - rst_controllers.rstPlotTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "rst_controllers.rstPlotTool.cli",
    "rst_controllers.rstPlotTool.apis",
]

_OPTIONAL_MODULES = [
    "rst_controllers.rstPlotTool.app",
    "rst_controllers.rstPlotTool.core",
    "rst_controllers.rstPlotTool.io",
    "rst_controllers.rstPlotTool.utils",
    "rst_controllers.rstPlotTool.plotting",
    "rst_controllers.rstPlotTool.design",
    "rst_controllers.rstPlotTool.examples",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "plotly.subplots",
    "scipy",
    "scipy.linalg",
    "scipy.signal",
    "sympy",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module still fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper performs the stricter
    check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> rstPlotTool -> rst_controllers -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(p: argparse.ArgumentParser) -> None:
    """Add RST CSV plotting arguments to ``p``."""
    p.add_argument("files", nargs="+", help="CSV file(s) or globs, e.g. out/*.csv.")

    p.add_argument("--overlay", dest="overlay", action="store_true", help="Plot all inputs on a single figure.")
    p.add_argument("--no-overlay", dest="overlay", action="store_false", help="Plot each input separately.")
    p.set_defaults(overlay=None)

    p.add_argument(
        "--backend",
        choices=["both", "mpl", "plotly"],
        default="both",
        help="Backend or backends to render.",
    )
    p.add_argument("--style", choices=["matlab", "light", "dark"], default="matlab", help="Plot style.")
    p.add_argument("--dpi", type=int, default=150, help="Matplotlib DPI.")

    p.add_argument("--kmin", type=float, help="Minimum k for plotting.")
    p.add_argument("--kmax", type=float, help="Maximum k for plotting.")
    p.add_argument(
        "--robust",
        type=float,
        default=0.995,
        help="Overlay y-limits from central quantiles. Use 1.0 to disable robust clipping.",
    )
    p.add_argument("--ylimY", nargs=2, type=float, metavar=("YMIN", "YMAX"), help="Explicit y-limits for r/y subplot.")
    p.add_argument("--ylimU", nargs=2, type=float, metavar=("UMIN", "UMAX"), help="Explicit y-limits for u subplot.")
    p.add_argument("--ylimE", nargs=2, type=float, metavar=("EMIN", "EMAX"), help="Explicit y-limits for e subplot.")
    p.add_argument("--clip", action="store_true", help="Clip traces to selected y-limits, useful for unstable overlays.")

    p.add_argument("--legend", choices=["compact", "full", "none"], default="compact", help="Legend mode in overlay.")
    p.add_argument("--include", help="Only include files matching this glob after positional expansion.")
    p.add_argument("--exclude", help="Exclude files matching this glob.")

    p.add_argument("--annotate", help="Design JSON, such as *_design.json, to show in a single-run plot.")
    p.add_argument("--title", help="Override figure title.")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="rst_controllers.rstPlotTool",
        description="Plot RST step-response CSVs with Matplotlib and/or Plotly.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="plot RST step-response CSV files",
        description="Plot RST step-response CSV files from rst.py using Matplotlib, Plotly, or both.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def args_to_request(ns: argparse.Namespace) -> RunRequest:
    """Convert parsed CLI arguments into a plotting ``RunRequest``."""
    ylims = YLimits(
        ylimY=tuple(ns.ylimY) if ns.ylimY else None,
        ylimU=tuple(ns.ylimU) if ns.ylimU else None,
        ylimE=tuple(ns.ylimE) if ns.ylimE else None,
    )
    filters = OverlayFilters(include=ns.include, exclude=ns.exclude)

    return RunRequest(
        files=list(ns.files),
        overlay=ns.overlay,
        backend=ns.backend,
        style=ns.style,
        dpi=ns.dpi,
        kmin=ns.kmin,
        kmax=ns.kmax,
        robust=ns.robust,
        ylimits=ylims,
        clip=ns.clip,
        legend=ns.legend,
        filters=filters,
        annotate=ns.annotate,
        title=ns.title,
    )


def _run_plot(ns: argparse.Namespace) -> int:
    """Run the RST plotting workflow."""
    app = RSTPlotApp()
    app.run(args_to_request(ns))
    return 0


def _run_sphinx_skel(ns: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(ns.dest, force=ns.force)

    print(f"Sphinx skeleton ready: {ns.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {ns.dest / '_static' / '.gitkeep'}")
    print(f"  {ns.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the rstPlotTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_plot(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
