#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`state_space.stateConverterTool`.

The CLI supports two usage styles:

1. Modern subcommand form::

       python -m state_space.stateConverterTool.cli run --example ogata_5_4

2. Historical no-subcommand form::

       python -m state_space.stateConverterTool.cli --example ogata_5_4

It also includes a ``sphinx-skel`` helper for generating a conservative,
GitHub Pages friendly Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path

import sympy as sp


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space.stateConverterTool.apis import RunRequest
    from state_space.stateConverterTool.app import StateConverterApp
    from state_space.stateConverterTool.design import fmt
    from state_space.stateConverterTool.io import parse_matrix, parse_scalar
else:
    from .apis import RunRequest
    from .app import StateConverterApp
    from .design import fmt
    from .io import parse_matrix, parse_scalar


_PACKAGE = "state_space.stateConverterTool"
_PROJECT = "Digital Control - state_space.stateConverterTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "state_space.stateConverterTool.cli",
    "state_space.stateConverterTool.apis",
]

_OPTIONAL_MODULES = [
    "state_space.stateConverterTool.app",
    "state_space.stateConverterTool.core",
    "state_space.stateConverterTool.io",
    "state_space.stateConverterTool.utils",
    "state_space.stateConverterTool.plotting",
    "state_space.stateConverterTool.design",
    "state_space.stateConverterTool.examples",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "scipy",
    "scipy.linalg",
    "sympy",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module still fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper performs the stricter
    check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> stateConverterTool -> state_space -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(ap: argparse.ArgumentParser) -> None:
    """Add ZOH state-conversion run arguments to ``ap``."""
    ap.add_argument("--A", help="Continuous-time system matrix A.")
    ap.add_argument("--B", help="Continuous-time input matrix B.")
    ap.add_argument("--C", help="Output matrix C.")
    ap.add_argument("--D", help="Feedthrough matrix D.")
    ap.add_argument("--T", help="Sampling period.")

    ap.add_argument("--digits", type=int, default=6, help="Digits for numeric printouts.")
    ap.add_argument("--evalf", type=int, default=None, help="Evaluate numeric inputs to floats with this many digits.")
    ap.add_argument("--no-simplify", action="store_true", help="Skip final symbolic simplify/together/cancel.")
    ap.add_argument("--force-inverse", action="store_true", help="Also compute and print (zI-G)^(-1) explicitly.")
    ap.add_argument("--no-fallback", action="store_true", help="Disable augmented-expm fallback when A is singular.")
    ap.add_argument("--latex", action="store_true", help="Emit LaTeX blocks to stdout.")
    ap.add_argument("--latex-out", help="Write LaTeX output to file. The ./out folder is recommended.")
    ap.add_argument(
        "--example",
        choices=["ogata_5_4", "ogata_5_5", "matlab_p318"],
        help="Run a built-in textbook/example case.",
    )


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="state_space.stateConverterTool",
        description="ZOH discretization and pulse-transfer F(z) tool with tidy one-line printing.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run ZOH discretization / state conversion",
        description="Run ZOH discretization and pulse-transfer F(z) conversion.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _validate_run_args(args: argparse.Namespace, parser: argparse.ArgumentParser) -> None:
    """Validate run arguments while preserving JSON-free historical behavior."""
    if args.example is None:
        missing = [name for name in ("A", "B", "C", "D", "T") if getattr(args, name) is None]
        if missing:
            parser.error("Missing required arguments: " + ", ".join(missing))


def _build_request(args: argparse.Namespace) -> RunRequest:
    """Build a ``RunRequest`` from parsed CLI arguments."""
    return RunRequest(
        A=parse_matrix(args.A) if args.A else None,
        B=parse_matrix(args.B) if args.B else None,
        C=parse_matrix(args.C) if args.C else None,
        D=parse_matrix(args.D) if args.D else None,
        T=parse_scalar(args.T) if args.T else None,
        example=args.example,
        digits=args.digits,
        evalf=args.evalf,
        simplify=not args.no_simplify,
        force_inverse=args.force_inverse,
        allow_singular_fallback=not args.no_fallback,
        want_latex=args.latex,
        latex_out=args.latex_out,
    )


def _print_results(args: argparse.Namespace, res: object) -> None:
    """Print the historical stateConverterTool result summary."""
    print("\n== Discrete-time (ZOH) result ==")
    print("G(T) =", fmt(res.G))
    print("H(T) =", fmt(res.H))

    if res.Finv is not None:
        print("(zI - G)^(-1) =", fmt(res.Finv))

    # For SISO output, unwrap 1x1.
    if res.F.shape == (1, 1):
        print("F(z) =", fmt(res.F[0, 0]))
    else:
        print("F(z) =", fmt(res.F))

    if res.latex and args.latex:
        print("\n== LaTeX ==")
        print(res.latex)


def _run_state_converter(args: argparse.Namespace, parser: argparse.ArgumentParser) -> int:
    """Run the ZOH state-conversion workflow."""
    _validate_run_args(args, parser)
    req = _build_request(args)

    app = StateConverterApp()
    try:
        res = app.run(req)
    except RuntimeError as exc:
        # Friendly error path, e.g. --no-fallback with singular A.
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    _print_results(args, res)
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)

    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the stateConverterTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_state_converter(args, parser)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
