# Generated by kalman_filters.kalmanFilterTool.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> kalmanFilterTool -> kalman_filters -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = 'digital-control - kalman_filters.kalmanFilterTool'
author = 'digital-control'

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = ['matplotlib', 'matplotlib.pyplot', 'plotly', 'plotly.graph_objects', 'scipy']
napoleon_google_docstring = True
napoleon_numpy_docstring = True
