#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`pole_placement.poleTool`.

The CLI supports two usage styles:

1. Modern subcommand form::

       python -m pole_placement.poleTool.cli run --json_in in/system.json --poles "0.5,0.6"

2. Historical no-subcommand form::

       python -m pole_placement.poleTool.cli --json_in in/system.json --poles "0.5,0.6"

It also includes a ``sphinx-skel`` helper for generating a conservative,
GitHub Pages friendly Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from pole_placement.poleTool.apis import RunRequest
    from pole_placement.poleTool.app import PolePlacementApp
else:
    from .apis import RunRequest
    from .app import PolePlacementApp


_PACKAGE = "pole_placement.poleTool"
_PROJECT = "Digital Control - pole_placement.poleTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "pole_placement.poleTool.cli",
    "pole_placement.poleTool.apis",
]

_OPTIONAL_MODULES = [
    "pole_placement.poleTool.app",
    "pole_placement.poleTool.core",
    "pole_placement.poleTool.io",
    "pole_placement.poleTool.utils",
    "pole_placement.poleTool.plotting",
    "pole_placement.poleTool.design",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "scipy",
    "scipy.linalg",
    "scipy.signal",
    "sympy",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module still fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper performs the stricter
    check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> poleTool -> pole_placement -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(ap: argparse.ArgumentParser) -> None:
    """Add pole-placement run arguments to ``ap``."""
    ap.add_argument("--A", type=str)
    ap.add_argument("--B", type=str)
    ap.add_argument("--C", type=str)
    ap.add_argument("--json_in", type=str, help="Load A, B, C from JSON file with keys A, B, C.")
    ap.add_argument("--poles", type=str, help='Desired poles, e.g. "0.5+0.5j,0.5-0.5j".')
    ap.add_argument("--deadbeat", action="store_true", help="Place all poles at 0 for SISO systems.")
    ap.add_argument(
        "--method",
        type=str,
        default="auto",
        choices=["auto", "ackermann", "ogata", "eigs", "place"],
        help="Pole-placement method.",
    )
    ap.add_argument("--plot", type=str, default="mpl", choices=["mpl", "plotly", "none"], help="Plotting backend.")
    ap.add_argument("--style", type=str, default="dots", choices=["dots", "stairs", "connected"], help="Plot style.")
    ap.add_argument("--samples", type=int, default=60, help="Number of simulation samples for plots/exports.")
    ap.add_argument("--pretty", action="store_true", help="Pretty-print internal results when supported.")
    ap.add_argument("--save_json", action="store_true", help="Save JSON result summary.")
    ap.add_argument("--save_csv", action="store_true", help="Save CSV result data.")
    ap.add_argument("--name", type=str, default="pole_place", help="Base name for output files.")
    ap.add_argument("--outdir", type=str, help="Override output directory. Default is package ./out.")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="pole_placement.poleTool",
        description="Discrete-time pole placement tool for Ogata-style design workflows.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run pole-placement analysis",
        description="Run discrete-time pole placement with optional plots and CSV/JSON exports.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _as_flat_list(value: object) -> object:
    """Return ``value.ravel().tolist()`` when available, otherwise return ``value``."""
    if hasattr(value, "ravel"):
        return value.ravel().tolist()
    return value


def _as_list(value: object) -> object:
    """Return ``value.tolist()`` when available, otherwise return ``value``."""
    if hasattr(value, "tolist"):
        return value.tolist()
    return value


def _run_pole_placement(ns: argparse.Namespace) -> int:
    """Run the pole-placement workflow."""
    req = RunRequest(
        A=ns.A,
        B=ns.B,
        C=ns.C,
        json_in=ns.json_in,
        poles=ns.poles,
        deadbeat=ns.deadbeat,
        method=ns.method,
        samples=ns.samples,
        plot=ns.plot,
        style=ns.style,
        pretty=ns.pretty,
        save_json=ns.save_json,
        save_csv=ns.save_csv,
        name=ns.name,
        outdir=ns.outdir,
    )

    app = PolePlacementApp()
    res = app.run(req)

    # Console summary: preserve the historical CLI behavior while being tolerant
    # of plain-list results in test/doc environments.
    K = res["K"]
    K0 = res["K0"]
    eigs = res["Acl_eigs"]

    print("=== RESULTS ===")
    print("method:", res["resolved_method"])
    print("K:", _as_flat_list(K))
    print("K0:", _as_flat_list(K0))
    print("eig(A-BK):", _as_list(eigs))
    print("placement error:", res["placement_error"])

    if res.get("plot_file"):
        print("plot:", res["plot_file"])
    if res.get("csv_file"):
        print("csv :", res["csv_file"])
    if res.get("json_file"):
        print("json:", res["json_file"])

    return 0


def _run_sphinx_skel(ns: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(ns.dest, force=ns.force)

    print(f"Sphinx skeleton ready: {ns.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {ns.dest / '_static' / '.gitkeep'}")
    print(f"  {ns.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the poleTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_pole_placement(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
