#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`system_design.juryTestTool`.

The CLI preserves the original Jury-test workflow while adding a
``sphinx-skel`` helper for GitHub Pages friendly Sphinx documentation.

Historical usage is preserved:

    python -m system_design.juryTestTool.cli --coeffs "1, -1.2, 0.07"
    python -m system_design.juryTestTool.cli run --coeffs "1, -1.2, 0.07"
    python -m system_design.juryTestTool.cli sphinx-skel docs/juryTestTool --force
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from system_design.juryTestTool.apis import RunRequest
    from system_design.juryTestTool.app import JuryTestApp
else:
    # Normal package execution.
    from .apis import RunRequest
    from .app import JuryTestApp


_PACKAGE = "system_design.juryTestTool"
_PROJECT = "Digital Control - system_design.juryTestTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "system_design.juryTestTool.cli",
    "system_design.juryTestTool.apis",
]

_OPTIONAL_MODULES = [
    "system_design.juryTestTool.app",
    "system_design.juryTestTool.core",
    "system_design.juryTestTool.io",
    "system_design.juryTestTool.utils",
    "system_design.juryTestTool.design",
    "system_design.juryTestTool.plotting",
    "system_design.juryTestTool.examples",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "scipy",
    "scipy.linalg",
    "scipy.signal",
    "sympy",
    "yaml",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` may report that a module exists even when the
    module fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper uses the stricter
    import check for generated API pages.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> juryTestTool -> system_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(p: argparse.ArgumentParser) -> None:
    """Add the original Jury-test workflow arguments to ``p``."""
    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument(
        "--coeffs",
        type=str,
        help=(
            "Comma/space-separated a0..an coefficients, high power to constant. "
            "Example: '1, -1.2, 0.07, 0.3, -0.08'"
        ),
    )
    src.add_argument(
        "--json_in",
        type=str,
        help="JSON in in/: { 'coeffs': [...], 'variable': 'z', 'param': 'K' }",
    )

    p.add_argument(
        "--method",
        choices=("jury", "schur", "bilinear", "all"),
        default="jury",
        help="Which method to run.",
    )
    p.add_argument(
        "--solve_range",
        action="store_true",
        help="Solve inequalities for parameter range when a parameter is present.",
    )
    p.add_argument(
        "--eval_K",
        type=float,
        default=None,
        help="Evaluate stability at this K and print roots.",
    )
    p.add_argument(
        "--T",
        type=float,
        default=None,
        help="Sampling period in seconds. If critical with |z|=1 and n=2, report omega_d = theta/T.",
    )
    p.add_argument(
        "--rational",
        action="store_true",
        help="Parse decimals as exact rationals.",
    )

    p.add_argument(
        "--abs_tol",
        type=float,
        default=1e-10,
        help="Absolute tolerance for boundary detection in inequalities.",
    )
    p.add_argument(
        "--rel_tol",
        type=float,
        default=1e-9,
        help="Relative tolerance for boundary detection in inequalities.",
    )
    p.add_argument(
        "--unit_tol",
        type=float,
        default=2e-6,
        help="Tolerance for |z| approximately equal to 1 via roots.",
    )

    p.add_argument(
        "--save_table",
        type=str,
        default=None,
        help="Save ASCII table or tables to out/ for Jury, Schur, or Routh results.",
    )
    p.add_argument(
        "--save_json",
        type=str,
        default=None,
        help="Save JSON report to out/.",
    )


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="system_design.juryTestTool",
        description="Stability checker: Jury, Schur-Cohn, Bilinear-Routh, and K-range solving.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run Jury/Schur-Cohn/Bilinear-Routh stability analysis",
        description="Run discrete-time stability checks and optional parameter-range solving.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_jury_test(args: argparse.Namespace) -> int:
    """Run the Jury-test application workflow."""
    req = RunRequest(
        coeffs=args.coeffs,
        json_in=args.json_in,
        method=args.method,
        solve_range=args.solve_range,
        eval_K=args.eval_K,
        T=args.T,
        rational=args.rational,
        abs_tol=args.abs_tol,
        rel_tol=args.rel_tol,
        unit_tol=args.unit_tol,
        save_table=args.save_table,
        save_json=args.save_json,
    )

    app = JuryTestApp()
    res = app.run(req)

    # Lightweight console summary, matching the historical CLI behavior.
    print(f"\nP(z): {res.polynomial}")
    print(f"Order: {res.order}")
    for name, method_result in res.methods.items():
        print(f"[{name}] Verdict: {method_result.verdict}")

    if res.eval_summary:
        print(
            "\n[Eval] K={K}, roots={roots}, radii={radii}, omega_d={omega_d}".format(
                **res.eval_summary
            )
        )

    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)

    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the juryTestTool command-line interface."""
    parser = build_parser()
    raw_args = list(sys.argv[1:] if argv is None else argv)

    # Preserve historical usage where the analysis arguments were supplied
    # directly with no explicit subcommand.
    if raw_args and raw_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
        raw_args = ["run", *raw_args]

    if not raw_args:
        parser.print_help()
        return 0

    args = parser.parse_args(raw_args)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd == "run":
        return _run_jury_test(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
