#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`z_transform.zTransformTool`.

The CLI supports two usage styles:

1. Modern subcommand form::

       python -m z_transform.zTransformTool.cli run --z --expr "a**k"

2. Historical no-subcommand form::

       python -m z_transform.zTransformTool.cli --z --expr "a**k"

It also includes a ``sphinx-skel`` helper for generating a conservative,
GitHub Pages friendly Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from z_transform.zTransformTool.apis import RunRequest
    from z_transform.zTransformTool.app import ZTApp
else:
    from .apis import RunRequest
    from .app import ZTApp


_PACKAGE = "z_transform.zTransformTool"
_PROJECT = "Digital Control - z_transform.zTransformTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "z_transform.zTransformTool.cli",
    "z_transform.zTransformTool.apis",
]

_OPTIONAL_MODULES = [
    "z_transform.zTransformTool.app",
    "z_transform.zTransformTool.core",
    "z_transform.zTransformTool.io",
    "z_transform.zTransformTool.utils",
    "z_transform.zTransformTool.plotting",
    "z_transform.zTransformTool.design",
    "z_transform.zTransformTool.examples",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "scipy",
    "scipy.linalg",
    "scipy.signal",
    "sympy",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module still fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper performs the stricter
    check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> zTransformTool -> z_transform -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(p: argparse.ArgumentParser) -> None:
    """Add Z-transform workflow arguments to ``p``."""
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--z", action="store_true", help="Forward Z-transform from x(k).")
    g.add_argument("--zt", action="store_true", help="Forward Z-transform from x(t), sampled as x(k)=x(kT).")
    g.add_argument("--iz", action="store_true", help="Inverse Z-transform, unilateral.")
    g.add_argument("--series", action="store_true", help="Direct-division series in z^{-1}.")
    g.add_argument("--residuez", action="store_true", help="SciPy residuez workflow in z^{-1}.")
    g.add_argument("--tf", action="store_true", help="Discrete transfer-function utilities.")
    g.add_argument("--diff", action="store_true", help="Solve a difference equation.")

    # Common
    p.add_argument("--expr", type=str, help="x(k) for --z.")
    p.add_argument("--xt", type=str, help="x(t) for --zt. Samples x(k)=x(kT).")
    p.add_argument("--X", type=str, help="X(z) for --iz or --series.")
    p.add_argument("--subs", type=str, help="Substitutions such as 'T=0.1,w=2,a=0.3,b=0.7'.")
    p.add_argument("--N", type=int, help="Sequence length or series order.")
    p.add_argument("--latex", action="store_true", help="Print LaTeX instead of ASCII.")
    p.add_argument("--pretty", action="store_true", help="No-op; pretty output is the default.")
    p.add_argument("--export_csv", type=str, help="CSV path for sequences. Relative paths go to package out/.")
    p.add_argument("--export_json", type=str, help="JSON path for sequences. Relative paths go to package out/.")

    # residuez / tf
    p.add_argument("--num", type=str, help="Numerator coefficients in z^{-1} powers.")
    p.add_argument("--den", type=str, help="Denominator coefficients in z^{-1} powers.")
    p.add_argument("--dt", type=float, default=1.0, help="Sampling period for transfer-function workflows.")
    p.add_argument("--impulse", action="store_true", help="Compute impulse response.")
    p.add_argument("--step", action="store_true", help="Compute step response.")
    p.add_argument("--u", type=str, help="Forced-response input sequence.")

    # difference equations
    p.add_argument("--rec", type=str, help="Full recurrence, e.g. 'Eq(x(k+2)+3*x(k+1)+2*x(k), 0)'.")
    p.add_argument("--a", type=str, help="LHS coefficients a0..an. Symbolic values are allowed.")
    p.add_argument("--rhs", type=str, help="Right-hand side in k. Optional.")
    p.add_argument("--ics", type=str, help="Initial conditions, e.g. 'x0=0,x1=1'.")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="z_transform.zTransformTool",
        description="Object-oriented Z-transform workflows.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run a Z-transform workflow",
        description=(
            "Run forward/inverse Z-transform, sampled continuous-time transform, "
            "series expansion, residuez, transfer-function utilities, or "
            "difference-equation solving."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _resolve_mode(args: argparse.Namespace) -> str | None:
    """Map mutually exclusive workflow flags to the app mode string."""
    if args.z:
        return "forward"
    if args.zt:
        return "forward_xt"
    if args.iz:
        return "inverse"
    if args.series:
        return "series"
    if args.residuez:
        return "residuez"
    if args.tf:
        return "tf"
    if args.diff:
        return "diff"
    return None


def _build_request(args: argparse.Namespace) -> RunRequest:
    """Build a ``RunRequest`` from parsed CLI arguments."""
    return RunRequest(
        mode=_resolve_mode(args),
        expr=args.expr,
        xt=args.xt,
        X=args.X,
        subs=args.subs,
        N=args.N,
        latex=args.latex,
        export_csv=args.export_csv,
        export_json=args.export_json,
        num=args.num,
        den=args.den,
        dt=args.dt,
        impulse=args.impulse,
        step=args.step,
        u=args.u,
        rec=args.rec,
        a=args.a,
        rhs=args.rhs,
        ics=args.ics,
    )


def _run_z_transform(args: argparse.Namespace) -> int:
    """Run the selected Z-transform workflow."""
    req = _build_request(args)
    app = ZTApp(print_boxes=True)
    app.run(req)
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)

    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the zTransformTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_z_transform(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
