#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`state_space.stateSpaceTool`.

The CLI supports two usage styles:

1. Modern subcommand form::

       python -m state_space.stateSpaceTool.cli run --example ogata_5_1

2. Historical no-subcommand form::

       python -m state_space.stateSpaceTool.cli --example ogata_5_1

It also includes a ``sphinx-skel`` helper for generating a conservative,
GitHub Pages friendly Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space.stateSpaceTool.apis import RunRequest
    from state_space.stateSpaceTool.app import StateSpaceApp
else:
    from .apis import RunRequest
    from .app import StateSpaceApp


_PACKAGE = "state_space.stateSpaceTool"
_PROJECT = "Digital Control - state_space.stateSpaceTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "state_space.stateSpaceTool.cli",
    "state_space.stateSpaceTool.apis",
]

_OPTIONAL_MODULES = [
    "state_space.stateSpaceTool.app",
    "state_space.stateSpaceTool.core",
    "state_space.stateSpaceTool.io",
    "state_space.stateSpaceTool.utils",
    "state_space.stateSpaceTool.plotting",
    "state_space.stateSpaceTool.design",
    "state_space.stateSpaceTool.examples",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "scipy",
    "scipy.linalg",
    "scipy.signal",
    "sympy",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module still fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper performs the stricter
    check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> stateSpaceTool -> state_space -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(ap: argparse.ArgumentParser) -> None:
    """Add state-space canonical-realization arguments to ``ap``."""
    ap.add_argument("--num", type=str, default=None, help="Numerator per --form: coefficients or SymPy expression in z.")
    ap.add_argument("--den", type=str, default=None, help="Denominator per --form: coefficients or SymPy expression in z.")
    ap.add_argument(
        "--form",
        type=str,
        default="auto",
        choices=["auto", "zmin1", "z", "expr", "zpk"],
        help="Input transfer-function form.",
    )
    ap.add_argument("--zeros", type=str, default=None, help="ZPK zeros, space or comma separated.")
    ap.add_argument("--poles", type=str, default=None, help="ZPK poles, space or comma separated.")
    ap.add_argument("--gain", type=float, default=None, help="ZPK gain.")
    ap.add_argument(
        "--forms",
        type=str,
        default="cont,obs,diag,jordan",
        help="Comma-separated subset of cont, obs, diag, jordan.",
    )
    ap.add_argument("--realblocks", action="store_true", help="Make real 2x2 blocks for simple complex conjugate pairs.")
    ap.add_argument("--dt", type=float, default=1.0, help="Sample time for python-control checks.")
    ap.add_argument("--json-out", type=str, default=None, help="Write realizations JSON to this path.")
    ap.add_argument("--latex", action="store_true", help="Emit LaTeX blocks to stdout.")
    ap.add_argument("--latex-out", type=str, default=None, help="Write LaTeX blocks to file.")
    ap.add_argument(
        "--check",
        type=str,
        default="brief",
        choices=["off", "brief", "full"],
        help="Roundtrip check verbosity.",
    )
    ap.add_argument("--example", type=str, default=None, choices=["ogata_5_1"], help="Convenience textbook loader.")
    ap.add_argument("--quiet", action="store_true", help="Reduce console output.")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="state_space.stateSpaceTool",
        description="Canonical realizations for discrete SISO pulse-transfer functions.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run canonical-realization generation",
        description="Generate controllable, observable, diagonal, and Jordan realizations.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _apply_example_defaults(args: argparse.Namespace) -> None:
    """Apply built-in example defaults in-place."""
    if args.example == "ogata_5_1":
        args.num = "z + 1"
        args.den = "z**2 + 1.3*z + 0.4"
        args.form = "expr"


def _build_request(args: argparse.Namespace) -> RunRequest:
    """Build a ``RunRequest`` from parsed CLI arguments."""
    return RunRequest(
        form=args.form,
        num=args.num,
        den=args.den,
        zeros=args.zeros,
        poles=args.poles,
        gain=args.gain,
        forms=args.forms,
        realblocks=args.realblocks,
        dt=args.dt,
        latex=args.latex,
        latex_out=args.latex_out,
        json_out=args.json_out,
        check=args.check,
        quiet=args.quiet,
    )


def _unjson_matrix(M: object):
    """Convert a JSON-compatible matrix back to a NumPy array."""
    import numpy as np

    arr = []
    has_complex_pairs = False
    for row in M:
        converted_row = []
        for value in row:
            if isinstance(value, (int, float)):
                converted_row.append(value)
            else:
                has_complex_pairs = True
                converted_row.append(complex(value[0], value[1]))
        arr.append(converted_row)

    dtype = complex if has_complex_pairs else float
    return np.array(arr, dtype=dtype)


def _print_transfer_function(args: argparse.Namespace) -> None:
    """Print the historical pulse-transfer-function console summary."""
    if args.quiet:
        return

    from state_space.stateSpaceTool.design import pretty_tf_lines
    from state_space.stateSpaceTool.io import parse_poly

    print("\n== Pulse transfer function ==")
    b, a = parse_poly(args.num, args.den, args.form, args.zeros, args.poles, args.gain)
    zm1, zdom = pretty_tf_lines(b, a)
    print("z^{-1} form  : H(z) =", zm1)
    print("z-domain form: H(z) =", zdom)


def _print_realizations(res: object) -> None:
    """Print state-space realizations from the app response."""
    from state_space.stateSpaceTool.design import pretty_ss_lines

    for key in ["cont", "obs", "diag", "jordan"]:
        if key not in res.realizations:
            continue

        R = res.realizations[key]
        A, B, C, D = map(_unjson_matrix, (R["A"], R["B"], R["C"], R["D"]))
        print(f"\n-- {key.capitalize()} --")
        x_line, y_line = pretty_ss_lines(A, B, C, D)
        print(x_line)
        print(y_line)


def _print_extra_outputs(args: argparse.Namespace, res: object) -> None:
    """Print LaTeX and check logs when requested."""
    if res.latex and args.latex:
        print("\n-- LaTeX --\n" + res.latex)

    if res.check_log and not args.quiet:
        print("\n" + res.check_log)


def _run_state_space(args: argparse.Namespace) -> int:
    """Run the canonical-realization workflow."""
    _apply_example_defaults(args)

    req = _build_request(args)
    app = StateSpaceApp()
    res = app.run(req)

    _print_transfer_function(args)
    _print_realizations(res)
    _print_extra_outputs(args, res)
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)

    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the stateSpaceTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_state_space(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
