#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`z_plane_analysis.discreteResponseTool`.

The CLI preserves the original one-shot discrete-response workflow while adding
an optional ``sphinx-skel`` helper for generating conservative, GitHub Pages
friendly Sphinx documentation files.

Supported entry points:

* ``python -m z_plane_analysis.discreteResponseTool.cli``
* ``python z_plane_analysis/discreteResponseTool/cli.py``

Historical no-subcommand usage is preserved. For example, the following still
routes to the run workflow:

``python -m z_plane_analysis.discreteResponseTool.cli --example37``

The explicit form is also supported:

``python -m z_plane_analysis.discreteResponseTool.cli run --example37``
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from z_plane_analysis.discreteResponseTool.apis import RunRequest
    from z_plane_analysis.discreteResponseTool.app import DiscreteResponseApp
else:
    # Normal package execution.
    from .apis import RunRequest
    from .app import DiscreteResponseApp


_PACKAGE = "z_plane_analysis.discreteResponseTool"
_PROJECT = "Digital Control - z_plane_analysis.discreteResponseTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "z_plane_analysis.discreteResponseTool.cli",
    "z_plane_analysis.discreteResponseTool.apis",
    "z_plane_analysis.discreteResponseTool.app",
]

_OPTIONAL_MODULES = [
    "z_plane_analysis.discreteResponseTool.core",
    "z_plane_analysis.discreteResponseTool.design",
    "z_plane_analysis.discreteResponseTool.io",
    "z_plane_analysis.discreteResponseTool.utils",
    "z_plane_analysis.discreteResponseTool.plotting",
    "z_plane_analysis.discreteResponseTool.examples",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "scipy",
    "scipy.linalg",
    "scipy.signal",
    "sympy",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can find a module even when importing it fails
    because an optional runtime dependency is missing. Sphinx autodoc needs
    modules that are safe to import, so this helper performs the stricter check.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> discreteResponseTool -> z_plane_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _parse_complex_token(text: str) -> complex:
    """Parse a CLI complex token without using ``eval``."""
    token = str(text).strip().replace("i", "j")
    try:
        return complex(token)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"Invalid complex pole token: {text!r}") from exc


def _add_run_arguments(ap: argparse.ArgumentParser) -> None:
    """Add the original discreteResponseTool run arguments to ``ap``."""
    ap.add_argument("--example37", action="store_true")
    ap.add_argument("--plant-num", type=float, nargs="+", dest="plant_num")
    ap.add_argument("--plant-den", type=float, nargs="+", dest="plant_den")
    ap.add_argument("--T", type=float)

    ap.add_argument("--Kp", type=float)
    ap.add_argument("--Ki", type=float)
    ap.add_argument("--Kd", type=float)
    ap.add_argument("--K", type=float)
    ap.add_argument("--Ti", type=float)
    ap.add_argument("--Td", type=float)

    ap.add_argument("--ctrl-numz", type=float, nargs="+", dest="ctrl_numz")
    ap.add_argument("--ctrl-denz", type=float, nargs="+", dest="ctrl_denz")

    ap.add_argument("--input", type=str, choices=["step", "ramp"], default="step")
    ap.add_argument("--ramp", action="store_true")
    ap.add_argument("--amp", type=float, default=1.0)
    ap.add_argument("--N", type=int, default=60)
    ap.add_argument("--cl-poles", type=str, nargs="+")

    ap.add_argument("--two-dof", action="store_true")
    ap.add_argument("--t-design", type=str, choices=["dc", "lag", "none", "custom"], default="dc")
    ap.add_argument("--t-beta", type=float, default=0.85)
    ap.add_argument("--t-numz", type=float, nargs="+")
    ap.add_argument("--t-denz", type=float, nargs="+")
    ap.add_argument("--pre-numz", type=float, nargs="+")
    ap.add_argument("--pre-denz", type=float, nargs="+")

    ap.add_argument("--matplotlib", type=str)
    ap.add_argument("--csv", type=str)
    ap.add_argument("--pzmap", type=str)
    ap.add_argument("--rlocus", type=str)
    ap.add_argument("--plotly-step", type=str)
    ap.add_argument("--plotly-pz", type=str)
    ap.add_argument("--plotly-rl", type=str)

    ap.add_argument("--kmin", type=float, default=0.0)
    ap.add_argument("--kmax", type=float, default=20.0)
    ap.add_argument("--rlocus-log", action="store_true")
    ap.add_argument("--rclip", type=float, default=2.5)
    ap.add_argument("--pzclip", type=float, default=2.0)

    ap.add_argument("--panel", type=str)
    ap.add_argument("--outdir", type=str, default="out")
    ap.add_argument("--print-tf", action="store_true")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="z_plane_analysis.discreteResponseTool",
        description="Discrete-time response / z-plane toolbox with plotting and Sphinx support.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run discrete-time response / z-plane analysis",
        description="Run the original discreteResponseTool workflow.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _build_run_request(args: argparse.Namespace) -> RunRequest:
    """Convert parsed CLI arguments into the application request object."""
    if getattr(args, "ramp", False):
        args.input = "ramp"

    cl_poles = None
    if args.cl_poles:
        cl_poles = [_parse_complex_token(s) for s in args.cl_poles]

    return RunRequest(
        example37=bool(args.example37),
        plant_num=args.plant_num,
        plant_den=args.plant_den,
        T=args.T,
        Kp=args.Kp,
        Ki=args.Ki,
        Kd=args.Kd,
        K=args.K,
        Ti=args.Ti,
        Td=args.Td,
        ctrl_numz=args.ctrl_numz,
        ctrl_denz=args.ctrl_denz,
        input=args.input,
        amp=args.amp,
        N=args.N,
        cl_poles=cl_poles,
        two_dof=bool(args.two_dof),
        t_design=args.t_design,
        t_beta=args.t_beta,
        t_numz=args.t_numz,
        t_denz=args.t_denz,
        pre_numz=args.pre_numz,
        pre_denz=args.pre_denz,
        matplotlib=args.matplotlib,
        csv=args.csv,
        pzmap=args.pzmap,
        rlocus=args.rlocus,
        plotly_step=args.plotly_step,
        plotly_pz=args.plotly_pz,
        plotly_rl=args.plotly_rl,
        kmin=args.kmin,
        kmax=args.kmax,
        rlocus_log=bool(args.rlocus_log),
        rclip=args.rclip,
        pzclip=args.pzclip,
        panel=args.panel,
        outdir=args.outdir,
        print_tf=bool(args.print_tf),
    )


def _run_discrete_response(args: argparse.Namespace) -> int:
    """Run the discreteResponseTool workflow."""
    req = _build_run_request(args)
    app = DiscreteResponseApp(req)
    app.run(
        matplotlib=req.matplotlib,
        csv=req.csv,
        pzmap=req.pzmap,
        rlocus=req.rlocus,
        plotly_step=req.plotly_step,
        plotly_pz=req.plotly_pz,
        plotly_rl=req.plotly_rl,
        panel=req.panel,
        outdir=req.outdir,
    )
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)

    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the discreteResponseTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        # Preserve historical no-subcommand usage:
        #   python -m z_plane_analysis.discreteResponseTool.cli --example37
        # and even bare execution, which used to run with default arguments.
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] in {"-h", "--help"}:
            parser.print_help()
            return 0
        args = parser.parse_args(["run", *legacy_args])

    if args.cmd == "run":
        return _run_discrete_response(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
