#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`polynomial_equations.polynomialTool`.

The CLI preserves the original polynomial-tool subcommands:

* ``solve``
* ``polydesign``
* ``rst``
* ``modelmatch``

It also adds a ``sphinx-skel`` helper for generating a conservative,
GitHub Pages friendly Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from polynomial_equations.polynomialTool.apis import RunRequest
    from polynomial_equations.polynomialTool.app import PolynomialApp
    from polynomial_equations.polynomialTool.io import parse_coeffs
else:
    from .apis import RunRequest
    from .app import PolynomialApp
    from .io import parse_coeffs


_PACKAGE = "polynomial_equations.polynomialTool"
_PROJECT = "Digital Control - polynomial_equations.polynomialTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "polynomial_equations.polynomialTool.cli",
    "polynomial_equations.polynomialTool.apis",
]

_OPTIONAL_MODULES = [
    "polynomial_equations.polynomialTool.app",
    "polynomial_equations.polynomialTool.core",
    "polynomial_equations.polynomialTool.io",
    "polynomial_equations.polynomialTool.utils",
    "polynomial_equations.polynomialTool.plotting",
    "polynomial_equations.polynomialTool.design",
    "polynomial_equations.polynomialTool.examples",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "scipy",
    "scipy.linalg",
    "scipy.signal",
    "sympy",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module still fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper performs the stricter
    check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> polynomialTool -> polynomial_equations -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_common(p: argparse.ArgumentParser) -> None:
    """Add arguments common to polynomialTool run commands."""
    p.add_argument("--A", required=True, help='Plant A(z^-1) coefficients in DESC order, e.g. "1,-2,1".')
    p.add_argument("--B", required=True, help='Plant B(z^-1) coefficients in DESC order, e.g. "0.02,0.02".')

    p.add_argument(
        "--layout",
        choices=["ogata", "desc"],
        default="ogata",
        help=(
            "Coefficient layout. 'ogata' builds the 2n x 2n Sylvester matrix "
            "from the book; 'desc' uses descending-power convolution blocks."
        ),
    )
    p.add_argument("--d", type=int, default=0, help="Relative degree / input delay.")
    p.add_argument("--degS", type=int, help="Override deg(S) for DESC layout.")
    p.add_argument("--degR", type=int, help="Override deg(R) for DESC layout.")

    # presentation
    p.add_argument("--pretty", action="store_true", help="Pretty-print alpha/beta where applicable.")
    p.add_argument("--show_E", action="store_true", help="Show the Sylvester matrix E when applicable.")

    # exports
    p.add_argument("--export_json", help="Export results to JSON file. Relative out/... paths resolve under package/out/.")
    p.add_argument("--export_csv", help="Export results to CSV file. Relative out/... paths resolve under package/out/.")

    # plotting/sim controls
    p.add_argument(
        "--backend",
        choices=["mpl", "plotly", "none"],
        default="none",
        help="Preview backend for step/ramp plots.",
    )
    p.add_argument("--save", help="Prefix path for saved plots/HTML. Relative out/... paths resolve under package/out/.")
    p.add_argument("--T", type=float, default=1.0, help="Sampling time for simulations.")
    p.add_argument("--kmax", type=int, default=40, help="Simulation length in samples.")

    # ogata parity handling
    p.add_argument(
        "--ogata_parity",
        action="store_true",
        help="Enable Ogata parity shift handling where supported.",
    )


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    ap = argparse.ArgumentParser(
        prog="polynomial_equations.polynomialTool",
        description="Polynomial Equations tool for Ogata Chapter 7 workflows.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = ap.add_subparsers(dest="cmd", required=True)

    # solve
    p_solve = sub.add_parser(
        "solve",
        help="compute alpha/beta from A, B, D",
        description="Compute alpha/beta from A, B, and D using Ogata or DESC layout.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_common(p_solve)
    p_solve.add_argument("--D", required=True, help='Right-hand-side polynomial D in DESC order, e.g. "1,0,0,0".')

    # polydesign
    p_pd = sub.add_parser(
        "polydesign",
        help="closed-loop preview using D directly or H/F/config",
        description="Closed-loop preview for step/ramp using either D directly or H, F, and config.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_common(p_pd)
    p_pd.add_argument("--D", help="Direct D polynomial in DESC order. If omitted, provide H, F, and config.")
    p_pd.add_argument("--H", help="Closed-loop numerator H in DESC order.")
    p_pd.add_argument("--F", help="Feedforward F in DESC order.")
    p_pd.add_argument("--config", type=int, choices=[1, 2], help="Controller configuration selector when using H and F.")

    # rst
    p_rst = sub.add_parser(
        "rst",
        help="RST design and preview",
        description="Run RST design and optional preview.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_common(p_rst)
    p_rst.add_argument("--H", required=True, help="Desired closed-loop numerator H in DESC order.")
    p_rst.add_argument("--F", required=True, help="Feedforward F in DESC order.")
    p_rst.add_argument("--rst_config", type=int, default=2, choices=[1, 2], help="RST configuration selector.")

    # modelmatch
    p_mm = sub.add_parser(
        "modelmatch",
        help="model matching with target G_model(z) and prefilter H1",
        description="Run model matching with target model G_model(z) and prefilter H1.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_common(p_mm)
    p_mm.add_argument("--Gmodel_num", required=True, help="Target model numerator in DESC order.")
    p_mm.add_argument("--Gmodel_den", required=True, help="Target model denominator in DESC order.")
    p_mm.add_argument("--H1", required=True, help="Prefilter H1 in DESC order.")
    p_mm.add_argument("--F", required=True, help="Feedforward F in DESC order.")

    # sphinx skeleton
    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return ap


def _ns_to_req(cmd: str, ns: argparse.Namespace) -> RunRequest:
    """Convert parsed CLI arguments into a ``RunRequest``."""
    # Parse all polynomial vectors safely.
    A = parse_coeffs(ns.A)
    B = parse_coeffs(ns.B)
    D = parse_coeffs(ns.D) if getattr(ns, "D", None) else None
    H = parse_coeffs(ns.H) if getattr(ns, "H", None) else None
    F = parse_coeffs(ns.F) if getattr(ns, "F", None) else None
    H1 = parse_coeffs(ns.H1) if getattr(ns, "H1", None) else None
    Gm_num = parse_coeffs(ns.Gmodel_num) if getattr(ns, "Gmodel_num", None) else None
    Gm_den = parse_coeffs(ns.Gmodel_den) if getattr(ns, "Gmodel_den", None) else None

    return RunRequest(
        mode=cmd,
        A=A,
        B=B,
        layout=ns.layout,
        d=ns.d,
        degS=ns.degS,
        degR=ns.degR,
        pretty=ns.pretty,
        show_E=getattr(ns, "show_E", False),
        export_json=getattr(ns, "export_json", None),
        export_csv=getattr(ns, "export_csv", None),
        backend=ns.backend,
        save=ns.save,
        T=ns.T,
        kmax=ns.kmax,
        D=D,
        H=H,
        F=F,
        config=getattr(ns, "config", None),
        ogata_parity=getattr(ns, "ogata_parity", False),
        Gmodel_num=Gm_num,
        Gmodel_den=Gm_den,
        H1=H1,
        rst_config=getattr(ns, "rst_config", 2),
    )


def _run_polynomial(ns: argparse.Namespace) -> int:
    """Run a polynomialTool workflow."""
    req = _ns_to_req(ns.cmd, ns)

    app = PolynomialApp()
    res = app.run(req)

    # Unified, compact stdout for alpha/beta if present.
    if isinstance(res, dict) and "alpha" in res and "beta" in res:
        import numpy as np

        print("alpha:", np.round(res["alpha"], 12))
        print("beta :", np.round(res["beta"], 12))

    return 0


def _run_sphinx_skel(ns: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(ns.dest, force=ns.force)

    print(f"Sphinx skeleton ready: {ns.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {ns.dest / '_static' / '.gitkeep'}")
    print(f"  {ns.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the polynomialTool command-line interface."""
    parser = build_parser()
    ns = parser.parse_args(argv)

    if ns.cmd == "sphinx-skel":
        return _run_sphinx_skel(ns)

    return _run_polynomial(ns)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
