# Generated by intro.adcTool.cli
project = "digitalControl – intro.adcTool"
extensions = ["sphinx.ext.autodoc", "sphinx.ext.napoleon", "sphinx.ext.viewcode"]
templates_path = ["_templates"]
exclude_patterns = []
html_theme = "furo"
