#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`pole_placement.observerTool`.

The CLI preserves the original observer-tool subcommands:

* ``design``
* ``closedloop``
* ``k0``
* ``select``
* ``sim``
* ``example``

It also adds a ``sphinx-skel`` helper for generating a conservative,
GitHub Pages friendly Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import json
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from pole_placement.observerTool.apis import (
        ClosedLoopRequest,
        DesignRequest,
        ExampleRequest,
        K0Request,
        SelectRequest,
        SimRequest,
    )
    from pole_placement.observerTool.app import ObserverApp
else:
    # Normal package execution.
    from .apis import (
        ClosedLoopRequest,
        DesignRequest,
        ExampleRequest,
        K0Request,
        SelectRequest,
        SimRequest,
    )
    from .app import ObserverApp


_PACKAGE = "pole_placement.observerTool"
_PROJECT = "Digital Control - pole_placement.observerTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "pole_placement.observerTool.cli",
    "pole_placement.observerTool.apis",
]

_OPTIONAL_MODULES = [
    "pole_placement.observerTool.app",
    "pole_placement.observerTool.core",
    "pole_placement.observerTool.io",
    "pole_placement.observerTool.utils",
    "pole_placement.observerTool.plotting",
    "pole_placement.observerTool.design",
    "pole_placement.observerTool.examples",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "scipy",
    "scipy.linalg",
    "scipy.signal",
    "sympy",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module still fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper performs the stricter
    check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> observerTool -> pole_placement -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    p = argparse.ArgumentParser(
        prog="pole_placement.observerTool",
        description=(
            "Observer design tool: prediction/current/minimum-order observer "
            "design, DLQE, closed-loop checks, K0 prefilter, observer-gain "
            "selection, simulations, and textbook examples."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    # design
    d = sub.add_parser(
        "design",
        help="design observer gains",
        description="Design observer gains for prediction, current, DLQE, or minimum-order observers.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    d.add_argument("--type", choices=["prediction", "current", "dlqe", "min"], required=True)
    d.add_argument("--A")
    d.add_argument("--C")
    d.add_argument("--method", choices=["place", "acker"], default="place")
    d.add_argument("--poles", help="Comma-separated poles for prediction/current/min.")
    d.add_argument("--B", help="Required for minimum-order observer design.")
    d.add_argument("--G", help="Process-noise input matrix for DLQE.")
    d.add_argument("--Qn", help="Process-noise covariance for DLQE.")
    d.add_argument("--Rn", help="Measurement-noise covariance for DLQE.")
    d.add_argument("--csv", help="Export CSV to out/...")
    d.add_argument("--out", help="Export JSON to out/...")

    # closed loop
    cl = sub.add_parser(
        "closedloop",
        help="check closed-loop poles and separation principle",
        description="Compute closed-loop poles and perform a separation-principle check.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    cl.add_argument("--A")
    cl.add_argument("--B")
    cl.add_argument("--C")
    cl.add_argument("--K")
    cl.add_argument("--L")
    cl.add_argument("--out", help="Export JSON to out/...")

    # k0
    k0 = sub.add_parser(
        "k0",
        help="compute SISO prefilter K0",
        description="Compute SISO prefilter K0 using state or Ogata mode.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    k0.add_argument("--A")
    k0.add_argument("--B")
    k0.add_argument("--C")
    k0.add_argument("--K")
    k0.add_argument("--L", help="Needed for Ogata mode.")
    k0.add_argument("--mode", choices=["state", "ogata"], default="state")
    k0.add_argument("--ogata-extra-gain", type=float, default=None)
    k0.add_argument("--out", help="Export JSON to out/...")

    # select
    sel = sub.add_parser(
        "select",
        help="select observer gain L",
        description="Select L via rule of thumb, DLQE, or grid sweep.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sel.add_argument("--A")
    sel.add_argument("--B")
    sel.add_argument("--C")
    sel.add_argument("--K")
    sel.add_argument("--method", choices=["place", "acker"], default="place")
    sel.add_argument("--rule-of-thumb", help="Comma poles of plant, e.g. '0.6+0.4j,0.6-0.4j'.")
    sel.add_argument("--speedup", type=float, default=5.0)
    sel.add_argument("--sweep", help="Pole sets separated by ';', each comma-separated.")
    sel.add_argument("--steps", type=int, default=200)
    sel.add_argument("--dlqe", action="store_true")
    sel.add_argument("--G")
    sel.add_argument("--Qn")
    sel.add_argument("--Rn")
    sel.add_argument("--csv", help="Export CSV of best L to out/...")
    sel.add_argument("--out", help="Export JSON summary to out/...")

    # sim
    sim = sub.add_parser(
        "sim",
        help="simulate plant, observer, and state feedback",
        description="Simulate plant + observer + state feedback with step/ramp references and optional automatic K0.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sim.add_argument("--A")
    sim.add_argument("--B")
    sim.add_argument("--C")
    sim.add_argument("--K")
    sim.add_argument("--L")
    sim.add_argument("--N", type=int, default=60)
    sim.add_argument("--Ts", type=float, default=1.0)
    sim.add_argument("--ref", choices=["none", "step", "ramp"], default="step")
    sim.add_argument("--K0", help="'auto' or numeric", default=None)
    sim.add_argument("--k0-mode", choices=["state", "ogata"], default="state")
    sim.add_argument("--ogata-extra-gain", type=float, default=None)
    sim.add_argument("--csv", help="Export CSV with t, y, u to out/...")
    sim.add_argument("--out", help="Export JSON to out/...")
    sim.add_argument("--plot", action="store_true", help="Show Matplotlib plots.")
    sim.add_argument("--plot-type", choices=["points", "stairs", "line"], default="points")
    sim.add_argument("--plotly", action="store_true", help="Show Plotly figure.")
    sim.add_argument("--html", help="Save Plotly HTML to out/...")

    # examples
    ex = sub.add_parser(
        "example",
        help="run textbook examples",
        description="Run textbook examples 6-9, 6-10, 6-11, or 6-12.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    ex.add_argument("--which", choices=["6-9", "6-10", "6-11", "6-12"], required=True)
    ex.add_argument("--Ts", type=float, default=0.2)

    # sphinx skeleton
    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return p


def _require(ns: argparse.Namespace, parser: argparse.ArgumentParser, names: tuple[str, ...]) -> None:
    """Raise a parser error if any named argument is missing."""
    for name in names:
        if getattr(ns, name) is None:
            parser.error(f"--{name} is required")


def _run_observer(ns: argparse.Namespace, parser: argparse.ArgumentParser) -> object:
    """Run the selected observerTool workflow and return the app output."""
    app = ObserverApp()

    if ns.cmd == "design":
        if ns.type in ("prediction", "current", "min") and not ns.poles:
            parser.error("--poles required for 'prediction', 'current', and 'min'.")
        if ns.type == "min" and not ns.B:
            parser.error("--B is required for minimum-order.")
        if ns.type == "dlqe" and not (ns.G and ns.Qn and ns.Rn):
            parser.error("--G, --Qn, --Rn are required for dlqe.")
        req = DesignRequest(
            kind=ns.type,
            A=ns.A,
            C=ns.C,
            poles=ns.poles,
            B=ns.B,
            method=ns.method,
            G=ns.G,
            Qn=ns.Qn,
            Rn=ns.Rn,
            csv=ns.csv,
            out=ns.out,
        )
        return app.run(req)

    if ns.cmd == "closedloop":
        _require(ns, parser, ("A", "B", "C", "K", "L"))
        req = ClosedLoopRequest(A=ns.A, B=ns.B, C=ns.C, K=ns.K, L=ns.L, out=ns.out)
        return app.run(req)

    if ns.cmd == "k0":
        _require(ns, parser, ("A", "B", "C", "K"))
        req = K0Request(
            A=ns.A,
            B=ns.B,
            C=ns.C,
            K=ns.K,
            L=ns.L,
            mode=ns.mode,
            ogata_extra_gain=ns.ogata_extra_gain,
            out=ns.out,
        )
        return app.run(req)

    if ns.cmd == "select":
        _require(ns, parser, ("A", "B", "C", "K"))
        req = SelectRequest(
            A=ns.A,
            B=ns.B,
            C=ns.C,
            K=ns.K,
            method=ns.method,
            rule_of_thumb=ns.rule_of_thumb,
            speedup=ns.speedup,
            sweep=ns.sweep,
            steps=ns.steps,
            dlqe=ns.dlqe,
            G=ns.G,
            Qn=ns.Qn,
            Rn=ns.Rn,
            csv=ns.csv,
            out=ns.out,
        )
        return app.run(req)

    if ns.cmd == "sim":
        _require(ns, parser, ("A", "B", "C", "K", "L"))
        req = SimRequest(
            A=ns.A,
            B=ns.B,
            C=ns.C,
            K=ns.K,
            L=ns.L,
            N=ns.N,
            Ts=ns.Ts,
            ref=ns.ref,
            K0=ns.K0,
            k0_mode=ns.k0_mode,
            ogata_extra_gain=ns.ogata_extra_gain,
            csv=ns.csv,
            out=ns.out,
            plot=ns.plot,
            plot_type=ns.plot_type,
            plotly=ns.plotly,
            html=ns.html,
        )
        return app.run(req)

    if ns.cmd == "example":
        req = ExampleRequest(which=ns.which, Ts=ns.Ts)
        return app.run(req)

    parser.error("Unknown command")
    return None


def _run_sphinx_skel(ns: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(ns.dest, force=ns.force)

    print(f"Sphinx skeleton ready: {ns.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {ns.dest / '_static' / '.gitkeep'}")
    print(f"  {ns.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the observerTool command-line interface."""
    parser = build_parser()
    ns = parser.parse_args(argv)

    if ns.cmd == "sphinx-skel":
        return _run_sphinx_skel(ns)

    out = _run_observer(ns, parser)

    # Print compact JSON to stdout, matching the historical CLI behavior.
    print(json.dumps(out, default=str, indent=2))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
