#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from pathlib import Path
from typing import Optional

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from introduction.zohTool.apis import RunRequest
    from introduction.zohTool.app import ZOHApp
else:
    from .apis import RunRequest
    from .app import ZOHApp


_PACKAGE = "introduction.zohTool"
_PROJECT = "digital-control - introduction.zohTool"
_AUTHOR = "digital-control"
_REQUIRED_MODULES = [
    "introduction.zohTool.cli",
    "introduction.zohTool.apis",
    "introduction.zohTool.app",
]
_OPTIONAL_MODULES = [
    "introduction.zohTool.core",
    "introduction.zohTool.design",
    "introduction.zohTool.io",
    "introduction.zohTool.utils",
    "introduction.zohTool.plotting",
]


def _available_modules() -> list[str]:
    """Return only modules that Python can import."""
    modules = list(_REQUIRED_MODULES)
    for mod in _OPTIONAL_MODULES:
        if importlib.util.find_spec(mod) is not None:
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text unless the file already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support folders and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> zohTool -> introduction -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build a Sphinx index page with safe heading lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that documents only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _available_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(ap: argparse.ArgumentParser) -> None:
    """Add the original ZOH simulation arguments to a parser."""
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--csv", help="input CSV with column 'u' and optional 'k'")
    src.add_argument(
        "--json",
        dest="json_spec",
        help="input JSON: list of numbers, list of {'u':..}, or {'vectors':[...]}",
    )

    ap.add_argument("--Ts", type=float, default=1e-3, help="sample period in seconds")
    ap.add_argument(
        "--delay",
        type=float,
        default=0.0,
        help="transport delay from sample to hold start in seconds",
    )
    ap.add_argument(
        "--droop-tau",
        type=float,
        default=float("inf"),
        help="hold droop time constant tau in seconds; use inf for ideal ZOH",
    )
    ap.add_argument("--offset", type=float, default=0.0, help="constant offset added to the held value")

    ap.add_argument("--units", default="V", help="units string for logs/CSV, e.g. V, A, or N")
    ap.add_argument(
        "--scale",
        type=float,
        default=1e6,
        help="scale for VCD integer output; default is 1e6 for micro-units",
    )
    ap.add_argument("--idx-bits", type=int, default=None, help="optional bit-width for the VCD index signal")

    ap.add_argument(
        "--in-dir",
        default="in",
        help="default input directory for relative filenames; default: in",
    )
    ap.add_argument(
        "--out-dir",
        default="out",
        help="default output directory for relative filenames; default: out",
    )

    ap.add_argument("--out", dest="out_csv", help="optional results CSV")
    ap.add_argument("--trace", dest="out_vcd", help="optional VCD file, e.g. zoh.vcd")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog=_PACKAGE,
        description="Zero-Order Hold (ZOH) simulator with CSV/JSON inputs and optional CSV/VCD outputs.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run a ZOH simulation",
        description="Run a Zero-Order Hold simulation from CSV or JSON input vectors.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_zoh(args: argparse.Namespace) -> int:
    """Run the ZOH application workflow."""
    req = RunRequest(
        csv=args.csv,
        json_spec=args.json_spec,
        Ts=args.Ts,
        delay=args.delay,
        droop_tau=args.droop_tau,
        offset=args.offset,
        units=args.units,
        scale=args.scale,
        idx_bits=args.idx_bits,
        in_dir=args.in_dir,
        out_dir=args.out_dir,
        out_csv=args.out_csv,
        out_vcd=args.out_vcd,
    )
    app = ZOHApp()
    res = app.run(req)

    print(
        f"ZOH with Ts={args.Ts:g} s, delay={args.delay:g} s, "
        f"droop_tau={args.droop_tau}, offset={args.offset} {args.units}"
    )
    for ev in res.events:
        print(
            f"[{ev.k}] t∈[{ev.t0:.6g},{ev.t1:.6g})  "
            f"u={ev.u_in:.6g} {args.units}  y0={ev.y0:.6g}  y1={ev.y1:.6g}"
        )

    for message in res.messages:
        print(message)

    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: Optional[list[str]] = None) -> int:
    """Run the zohTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_zoh(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
