# Generated by quadratic_control.quadraticTool.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> quadraticTool -> quadratic_control -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = 'Digital Control - quadratic_control.quadraticTool'
author = 'Digital Control'

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = ['control', 'matplotlib', 'matplotlib.pyplot', 'numpy', 'pandas', 'plotly', 'plotly.graph_objects', 'scipy', 'scipy.linalg', 'scipy.integrate', 'scipy.optimize', 'sympy', 'yaml']
napoleon_google_docstring = True
napoleon_numpy_docstring = True
