#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations
import argparse, os, sys
from pathlib import Path

# ---------- Import shim so `python -m intro.adcTool.cli` AND `python cli.py` both work ----------
if __package__ in (None, ""):
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)
    from intro.adcTool.apis import RunRequest
    from intro.adcTool.app import ADCApp
else:
    from .apis import RunRequest
    from .app import ADCApp


# ------------------------------ helpers -------------------------------- #

def _add_run_options(ap: argparse.ArgumentParser) -> None:
    ap.add_argument('--type', dest='adc_type', choices=['counter', 'sar'], required=True, help='ADC type')
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument('--csv', help="CSV with column 'vin'")
    src.add_argument('--json', help="JSON file or inline JSON of VIN values")

    ap.add_argument('--nbits', type=int, default=10)
    ap.add_argument('--vref', type=float, default=3.3)
    ap.add_argument('--comp-offset', type=float, default=0.0)
    ap.add_argument('--dac-gain', type=float, default=1.0)
    ap.add_argument('--dac-offset', type=float, default=0.0)
    ap.add_argument('--jitter-rms', type=float, default=0.0)
    ap.add_argument('--radix', choices=['dec', 'hex', 'bin', 'all'], default='dec')

    # timing
    ap.add_argument('--tclk', type=float, default=1e-6, help='Counter ADC clock period')
    ap.add_argument('--tbit', type=float, default=1e-6, help='SAR ADC bit decision period')

    # dir policy
    ap.add_argument('--in-dir', default='in')
    ap.add_argument('--out-dir', default='out')

    # outputs
    ap.add_argument('--out', dest='out_csv', help='Results CSV')
    ap.add_argument('--trace', dest='trace_vcd', help='VCD for last conversion')
    ap.add_argument('--trace-all', dest='trace_all_vcd', help='VCD accumulating all conversions')


def _write(path: Path, text: str, *, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


# ------------------------------ parser --------------------------------- #

def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="intro.adcTool — Counter & SAR ADC simulators")
    sub = ap.add_subparsers(dest="cmd")

    # keep old CLI via 'run' subcommand
    run = sub.add_parser("run", help="Run ADC simulation (back-compatible)")
    _add_run_options(run)

    # new: create Sphinx docs skeleton
    sk = sub.add_parser("sphinx-skel", help="Create a minimal Sphinx docs skeleton")
    sk.add_argument("dest", nargs="?", default="docs", help="Destination (default: docs)")
    sk.add_argument("--force", action="store_true", help="Overwrite existing files")

    return ap


# ------------------------------ commands -------------------------------- #

def _cmd_run(ns: argparse.Namespace) -> None:
    req = RunRequest(
        adc_type=ns.adc_type, csv=ns.csv, json=ns.json,
        nbits=ns.nbits, vref=ns.vref,
        comp_offset=ns.comp_offset, dac_gain=ns.dac_gain, dac_offset=ns.dac_offset,
        jitter_rms=ns.jitter_rms, radix=ns.radix,
        tclk=ns.tclk, tbit=ns.tbit,
        in_dir=ns.in_dir, out_dir=ns.out_dir,
        out_csv=ns.out_csv, trace_vcd=ns.trace_vcd, trace_all_vcd=ns.trace_all_vcd,
    )
    ADCApp().run(req)


def _cmd_sphinx_skel(ns: argparse.Namespace) -> None:
    dest = Path(ns.dest)
    (dest / "_templates").mkdir(parents=True, exist_ok=True)
    (dest / "_static").mkdir(parents=True, exist_ok=True)

    conf = (
        '# Generated by intro.adcTool.cli\n'
        'project = "digitalControl – intro.adcTool"\n'
        'extensions = ["sphinx.ext.autodoc", "sphinx.ext.napoleon", "sphinx.ext.viewcode"]\n'
        'templates_path = ["_templates"]\n'
        'exclude_patterns = []\n'
        'html_theme = "furo"\n'
    )
    index = (
        ".. intro.adcTool documentation master file\n\n"
        "Welcome to intro.adcTool’s docs!\n"
        "=================================\n\n"
        ".. toctree::\n"
        "   :maxdepth: 2\n"
        "   :caption: Contents:\n\n"
        "   api\n"
    )
    # list only modules you actually have; adjust freely
    api = (
        "API Reference\n"
        "=============\n\n"
        ".. automodule:: intro.adcTool.app\n   :members:\n   :undoc-members:\n\n"
        ".. automodule:: intro.adcTool.apis\n   :members:\n   :undoc-members:\n"
        ".. automodule:: intro.adcTool.core\n   :members:\n   :undoc-members:\n"
        ".. automodule:: intro.adcTool.io\n   :members:\n   :undoc-members:\n"
        ".. automodule:: intro.adcTool.utils\n   :members:\n   :undoc-members:\n"
    )
    makefile = (
        "# Minimal Sphinx Makefile\n"
        ".PHONY: html clean\n"
        "html:\n\t+sphinx-build -b html . _build/html\n"
        "clean:\n\t+rm -rf _build\n"
    )

    _write(dest / "conf.py", conf, overwrite=ns.force)
    _write(dest / "index.rst", index, overwrite=ns.force)
    _write(dest / "api.rst", api, overwrite=ns.force)
    _write(dest / "Makefile", makefile, overwrite=ns.force)
    print(str(dest))


# ------------------------------ entrypoint ------------------------------ #

def main(argv=None):
    ap = build_parser()

    # Back-compat “dirty trick”: if user calls without a subcommand,
    # pretend they meant `run` and re-parse.
    if isinstance(argv, (list, tuple)):
        args_list = list(argv)
    else:
        args_list = sys.argv[1:]

    if args_list and args_list[0] in ("run", "sphinx-skel"):
        ns = ap.parse_args(args_list)
    else:
        # insert default subcommand
        ns = ap.parse_args(["run", *args_list])

    if ns.cmd == "sphinx-skel":
        _cmd_sphinx_skel(ns)
    else:
        _cmd_run(ns)


if __name__ == "__main__":
    main()
