#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`pole_placement.transformationTool`.

The CLI supports two usage styles:

1. Modern subcommand form::

       python -m pole_placement.transformationTool.cli run --json in/system.json --to-ccf

2. Historical no-subcommand form::

       python -m pole_placement.transformationTool.cli --json in/system.json --to-ccf

It also includes a ``sphinx-skel`` helper for generating a conservative,
GitHub Pages friendly Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path

import numpy as np


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from pole_placement.transformationTool.apis import RunRequest
    from pole_placement.transformationTool.app import TransformationApp
    from pole_placement.transformationTool.io import load_from_json, parse_matrix
else:
    from .apis import RunRequest
    from .app import TransformationApp
    from .io import load_from_json, parse_matrix


_PACKAGE = "pole_placement.transformationTool"
_PROJECT = "Digital Control - pole_placement.transformationTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "pole_placement.transformationTool.cli",
    "pole_placement.transformationTool.apis",
]

_OPTIONAL_MODULES = [
    "pole_placement.transformationTool.app",
    "pole_placement.transformationTool.core",
    "pole_placement.transformationTool.io",
    "pole_placement.transformationTool.utils",
    "pole_placement.transformationTool.plotting",
    "pole_placement.transformationTool.design",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "scipy",
    "scipy.linalg",
    "scipy.signal",
    "sympy",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module still fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper performs the stricter
    check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> transformationTool -> pole_placement -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(p: argparse.ArgumentParser) -> None:
    """Add canonical-form transformation arguments to ``p``."""
    g_in = p.add_mutually_exclusive_group(required=True)
    g_in.add_argument("--json", type=str, help="Path to in/<file>.json containing A, B, C, D.")
    g_in.add_argument("--A", type=str, help='Matrix, e.g. "0 1; -2 -3".')

    p.add_argument("--B", type=str, default=None, help='Matrix, e.g. "0; 1" (n×1 for SISO).')
    p.add_argument("--C", type=str, default=None, help='Matrix, e.g. "1 0" (1×n for SISO).')
    p.add_argument("--D", type=str, default=None, help='Matrix, e.g. "0".')

    p.add_argument("--name", type=str, default="transform", help="Base name for outputs under out/.")
    p.add_argument("--pretty", action="store_true", help="Pretty-print matrices.")
    p.add_argument("--save-json", action="store_true", help="Save transformed systems to out/<name>_*.json.")
    p.add_argument("--save-csv", action="store_true", help="Save transformed matrices as CSV.")

    p.add_argument("--to-ccf", action="store_true", help="Transform to controllable canonical form (SISO).")
    p.add_argument("--to-ocf", action="store_true", help="Transform to observable canonical form (SISO).")
    p.add_argument("--to-diag", action="store_true", help="Transform to diagonal canonical form for distinct eigenvalues.")
    p.add_argument("--to-jordan", action="store_true", help="Transform to Jordan form using SymPy.")

    p.add_argument("--check-invariance", action="store_true", help="Show controllability/observability rank invariance after transform.")
    p.add_argument("--show-tf", action="store_true", help="For SISO systems, print numerator/denominator coefficients (b, a).")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="pole_placement.transformationTool",
        description="Canonical-form transformations for Ogata-style state-space workflows.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run canonical-form transformations",
        description="Run controllable, observable, diagonal, or Jordan canonical-form transformations.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _coerce_loaded_or_inline_system(args: argparse.Namespace) -> tuple[np.ndarray, object, object, object]:
    """Load the system from JSON or parse inline matrices."""
    if args.json:
        return load_from_json(args.json)

    A = parse_matrix(args.A)
    B = parse_matrix(args.B) if args.B else None
    C = parse_matrix(args.C) if args.C else None
    D = parse_matrix(args.D) if args.D else None

    if B is not None and getattr(B, "ndim", None) == 1:
        B = B.reshape(-1, 1)
    if C is not None and getattr(C, "ndim", None) == 1:
        C = C.reshape(1, -1)
    if D is not None and getattr(D, "ndim", None) == 0:
        D = D.reshape(1, 1)

    return A, B, C, D


def _run_transformation(args: argparse.Namespace) -> int:
    """Run the canonical-form transformation workflow."""
    A, B, C, D = _coerce_loaded_or_inline_system(args)

    req = RunRequest(
        A=A,
        B=B,
        C=C,
        D=D,
        json_in=args.json,
        to_ccf=args.to_ccf,
        to_ocf=args.to_ocf,
        to_diag=args.to_diag,
        to_jordan=args.to_jordan,
        show_tf=args.show_tf,
        check_invariance=args.check_invariance,
        pretty=args.pretty,
        name=args.name,
        save_json=args.save_json,
        save_csv=args.save_csv,
    )

    app = TransformationApp()
    app.run(req)
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)

    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the transformationTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_transformation(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
