#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`quadratic_control.quadraticTool`.

The CLI preserves the original YAML-driven ``solve`` workflow and adds a
``sphinx-skel`` helper for generating a conservative, GitHub Pages friendly
Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path
from typing import Dict


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from quadratic_control.quadraticTool.apis import RunRequest
    from quadratic_control.quadraticTool.app import QuadraticApp
    from quadratic_control.quadraticTool.utils import out_path, setup_logging
else:
    from .apis import RunRequest
    from .app import QuadraticApp
    from .utils import out_path, setup_logging


_PACKAGE = "quadratic_control.quadraticTool"
_PROJECT = "Digital Control - quadratic_control.quadraticTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "quadratic_control.quadraticTool.cli",
    "quadratic_control.quadraticTool.apis",
]

_OPTIONAL_MODULES = [
    "quadratic_control.quadraticTool.app",
    "quadratic_control.quadraticTool.core",
    "quadratic_control.quadraticTool.io",
    "quadratic_control.quadraticTool.utils",
    "quadratic_control.quadraticTool.plotting",
    "quadratic_control.quadraticTool.design",
    "quadratic_control.quadraticTool.examples",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "scipy",
    "scipy.linalg",
    "scipy.integrate",
    "scipy.optimize",
    "sympy",
    "yaml",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module still fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper performs the stricter
    check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> quadraticTool -> quadratic_control -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _parse_params(pairs: list[str] | None) -> Dict[str, float]:
    """Parse repeated ``key=value`` CLI overrides into floats.

    Malformed entries are ignored to preserve the original forgiving behavior;
    YAML remains the source of truth for complete case definitions.
    """
    params: Dict[str, float] = {}
    if not pairs:
        return params

    for item in pairs:
        if "=" not in item:
            continue
        key, value = item.split("=", 1)
        key = key.strip()
        try:
            params[key] = float(value)
        except ValueError:
            continue

    return params


def _add_solve_arguments(p_solve: argparse.ArgumentParser) -> None:
    """Add YAML-driven quadratic-control solve arguments."""
    p_solve.add_argument("--infile", "-i", required=True, help="Path to YAML config file.")
    p_solve.add_argument("--name", "-n", required=True, help="Case name, used as the output folder name.")
    p_solve.add_argument(
        "--outdir",
        "-o",
        default=out_path(),
        help="Base output directory. Default is the package out/ directory.",
    )
    p_solve.add_argument(
        "--plot",
        choices=("none", "mpl", "plotly"),
        default="none",
        help="Optional plot output.",
    )
    p_solve.add_argument(
        "--param",
        "-p",
        action="append",
        default=[],
        help="Override YAML params as key=value. Repeatable.",
    )
    p_solve.add_argument(
        "--sweep",
        help="Optional sweep spec formatted as name=start:stop:points. Overrides YAML sweep if given.",
    )


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="quadratic_control.quadraticTool",
        description="Quadratic optimal-control utilities.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    # YAML-driven run. The actual solver mode comes from YAML.
    p_solve = sub.add_parser(
        "solve",
        help="run using a YAML infile",
        description="Run a quadratic-control case using a YAML config file. The mode is specified in YAML.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_solve_arguments(p_solve)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_solve(args: argparse.Namespace) -> int:
    """Run the YAML-driven quadratic-control workflow."""
    params = _parse_params(args.param)

    # req.mode is only a fallback; YAML's mode takes precedence.
    req = RunRequest(
        mode="fh-dt",
        infile=args.infile,
        name=args.name,
        outdir=args.outdir,
        plot=args.plot,
        params=params,
        sweep=args.sweep,
    )
    out_case = QuadraticApp().run(req)
    print(out_case)
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)

    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the quadraticTool command-line interface."""
    setup_logging("INFO")

    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd == "solve":
        return _run_solve(args)

    parser.error("Unknown command")
    return 2


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
