#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`rst_controllers.rstTool`.

The CLI supports two usage styles:

1. Modern subcommand form::

       python -m rst_controllers.rstTool.cli run --in_json case.json --pretty

2. Historical no-subcommand form::

       python -m rst_controllers.rstTool.cli --in_json case.json --pretty

It also includes a ``sphinx-skel`` helper for generating a conservative,
GitHub Pages friendly Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from rst_controllers.rstTool.apis import RunRequest
    from rst_controllers.rstTool.app import RSTApp
    from rst_controllers.rstTool.design import diff_eq_strings, poly_to_str
    from rst_controllers.rstTool.io import parse_coeffs, parse_complex_list
else:
    from .apis import RunRequest
    from .app import RSTApp
    from .design import diff_eq_strings, poly_to_str
    from .io import parse_coeffs, parse_complex_list


_PACKAGE = "rst_controllers.rstTool"
_PROJECT = "Digital Control - rst_controllers.rstTool"
_AUTHOR = "Digital Control"

_REQUIRED_MODULES = [
    "rst_controllers.rstTool.cli",
    "rst_controllers.rstTool.apis",
]

_OPTIONAL_MODULES = [
    "rst_controllers.rstTool.app",
    "rst_controllers.rstTool.core",
    "rst_controllers.rstTool.io",
    "rst_controllers.rstTool.utils",
    "rst_controllers.rstTool.plotting",
    "rst_controllers.rstTool.design",
    "rst_controllers.rstTool.examples",
]

_AUTODOC_MOCK_IMPORTS = [
    "control",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "plotly.subplots",
    "scipy",
    "scipy.linalg",
    "scipy.signal",
    "sympy",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module still fails during import because an optional dependency is missing.
    Sphinx autodoc needs importable modules, so this helper performs the stricter
    check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> rstTool -> rst_controllers -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(p: argparse.ArgumentParser) -> None:
    """Add RST design and simulation arguments to ``p``."""
    # NOTE: --A and --B are optional to allow JSON-only runs.
    p.add_argument("--A", help='A(q) coefficients where q=z^-1, e.g. "1 -0.8".')
    p.add_argument("--B", help='B(q) coefficients, e.g. "0.5".')
    p.add_argument("--d", type=int, default=0, help="Input delay. Must be greater than or equal to 0.")
    p.add_argument("--Ts", type=float, default=1.0, help="Sampling period for s-to-z mapping.")

    # Target
    g = p.add_mutually_exclusive_group(required=False)
    g.add_argument("--Acl", help="Target A_cl(q) coefficients directly.")
    g.add_argument("--poles", help='Target z-plane poles, space or comma separated, e.g. "0.6 0.6".')
    g.add_argument("--spoles", help='Target s-plane poles mapped with z=exp(s*Ts), e.g. "-3+4j -3-4j".')
    p.add_argument("--Ac", help="Ac(q) coefficients.")
    p.add_argument("--Ao", help="Ao(q) coefficients.")

    # Degrees / policy
    p.add_argument("--degS", type=int, help="Degree of S(q). Overrides automatic degree selection.")
    p.add_argument("--degR", type=int, help="Degree of R(q). Overrides automatic degree selection.")
    p.add_argument("--alloc", choices=["S", "R"], default="S", help="Where to allocate extra degree.")
    p.add_argument("--integrator", action="store_true", help="Include (1 - q) in S path.")

    # Prefilter
    p.add_argument("--Tmode", choices=["unity_dc", "ac", "manual"], default="unity_dc", help="T selection mode.")
    p.add_argument("--T", help="Manual T(q) if --Tmode=manual.")

    # Simulation
    p.add_argument("--step", type=int, default=200, help="Simulation length N in samples.")
    p.add_argument("--r_step", type=float, default=1.0, help="Reference step amplitude.")
    p.add_argument("--v_step", type=float, default=0.0, help="Output disturbance step amplitude.")
    p.add_argument("--v_k0", type=int, default=0, help="Disturbance step start index k0.")
    p.add_argument("--noise", type=float, default=0.0, help="Measurement-noise sigma.")

    # I/O
    p.add_argument("--in_json", help="Load spec JSON. Relative names are looked up under rst_controllers/rstTool/in by default.")
    p.add_argument("--export_json", nargs="?", const="rst_design.json", help="Export design pack JSON to out/<name>.")
    p.add_argument("--save_csv", nargs="?", const="rst.csv", help="Save CSV with k, r, y, u, v to out/<name>.")

    p.add_argument("--pretty", action="store_true", help="Pretty console output.")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="rst_controllers.rstTool",
        description="RST design and simulation tool using q=z^-1 notation.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run RST design and simulation",
        description="Run RST controller design and simulation, with optional JSON/CSV export.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _build_request(args: argparse.Namespace) -> RunRequest:
    """Build a ``RunRequest`` from parsed CLI arguments."""
    return RunRequest(
        A=(parse_coeffs(args.A).tolist() if args.A else None),
        B=(parse_coeffs(args.B).tolist() if args.B else None),
        d=int(args.d),
        Ts=float(args.Ts),
        Acl=(parse_coeffs(args.Acl).tolist() if args.Acl else None),
        poles=(parse_complex_list(args.poles) if args.poles else None),
        spoles=(parse_complex_list(args.spoles) if args.spoles else None),
        Ac=(parse_coeffs(args.Ac).tolist() if args.Ac else None),
        Ao=(parse_coeffs(args.Ao).tolist() if args.Ao else None),
        degS=(int(args.degS) if args.degS is not None else None),
        degR=(int(args.degR) if args.degR is not None else None),
        alloc=args.alloc,
        integrator=bool(args.integrator),
        Tmode=args.Tmode,
        T=(parse_coeffs(args.T).tolist() if (args.Tmode == "manual" and args.T) else None),
        N=int(args.step),
        r_step=float(args.r_step),
        v_step=float(args.v_step),
        v_k0=int(args.v_k0),
        noise_sigma=float(args.noise),
        in_json=args.in_json,
        export_json=(args.export_json if args.export_json else None),
        save_csv=(args.save_csv if args.save_csv else None),
        pretty=bool(args.pretty),
    )


def _print_pretty_results(args: argparse.Namespace, res: object) -> None:
    """Print the historical pretty RST summary."""
    if not args.pretty:
        return

    import numpy as np

    print("\n== Controller (RST) ==")
    print(f"S(q) = {poly_to_str(res.S)}")
    print(f"R(q) = {poly_to_str(res.R)}")
    print(f"T(q) = {poly_to_str(res.Tq)}  [mode={args.Tmode}, alloc={args.alloc}]")

    ctrl, ueq = diff_eq_strings(np.array(res.R), np.array(res.S), np.array(res.Tq))
    print("\n-- Control law --")
    print(ctrl)
    print(ueq)

    print(f"\nSSE: {res.sse:.6g}, y_final={res.y_final:.6g}, u_final={res.u_final:.6g}")
    if res.csv_path:
        print(f"Saved CSV: {res.csv_path}")
    if res.json_path:
        print(f"Exported JSON: {res.json_path}")


def _run_rst(args: argparse.Namespace) -> int:
    """Run the RST design and simulation workflow."""
    req = _build_request(args)
    app = RSTApp()
    res = app.run(req)
    _print_pretty_results(args, res)
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)

    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the rstTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_rst(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
