#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Command-line interface for :mod:`introduction.dacTool`.

The CLI supports the original DAC simulation workflows and a deploy-safe
``sphinx-skel`` helper used by GitHub Pages / Sphinx documentation builds.
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from pathlib import Path
from typing import Iterable

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from introduction.dacTool.apis import RunRequest
    from introduction.dacTool.app import run as run_app
else:
    from .apis import RunRequest
    from .app import run as run_app


_PACKAGE = "introduction.dacTool"
_PROJECT = "digital-control - introduction.dacTool"
_AUTHOR = "digital-control"
_REQUIRED_MODULES = [
    "introduction.dacTool.cli",
    "introduction.dacTool.apis",
    "introduction.dacTool.app",
    "introduction.dacTool.core",
    "introduction.dacTool.design",
    "introduction.dacTool.io",
    "introduction.dacTool.utils",
]
_OPTIONAL_MODULES = [
    "introduction.dacTool.plotting",
    "introduction.dacTool.gui",
    "introduction.dacTool.gui_core",
    "introduction.dacTool.gui_utils",
]


# -----------------------------------------------------------------------------
# Sphinx skeleton helpers
# -----------------------------------------------------------------------------


def _available_modules() -> list[str]:
    """Return required modules plus optional modules that Python can import."""
    modules = list(_REQUIRED_MODULES)
    for mod in _OPTIONAL_MODULES:
        if importlib.util.find_spec(mod) is not None:
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support folders and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file for GitHub Pages."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# Expected docs location: introduction/dacTool/docs
# docs -> dacTool -> introduction -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build a Sphinx index page with safe heading lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that documents only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _available_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


# -----------------------------------------------------------------------------
# DAC run helpers
# -----------------------------------------------------------------------------


def add_common(ap: argparse.ArgumentParser) -> None:
    """Add arguments shared by R-2R and weighted-resistor DAC workflows."""
    ap.add_argument("--nbits", type=int, default=10, help="Number of DAC bits.")
    ap.add_argument("--vref", type=float, default=3.3, help="Reference voltage in volts.")
    ap.add_argument("--csv", help="CSV with 'code' or per-bit b0..b{n-1} columns.")
    ap.add_argument(
        "--json",
        dest="jspec",
        help="JSON inline value or path: list of integer codes or per-bit dictionaries.",
    )
    ap.add_argument("--tupd", type=float, default=1e-6, help="Update period in seconds for traces.")
    ap.add_argument("--in-dir", default="in", help="Input directory for relative input files.")
    ap.add_argument("--out-dir", default="out", help="Output directory for relative output files.")
    ap.add_argument("--out", dest="out_csv", help="Results CSV output path.")
    ap.add_argument("--trace", dest="out_vcd", help="VCD trace output path.")
    ap.add_argument("--trace-all", dest="out_vcd_all", help="Aggregate VCD trace output path.")
    ap.add_argument(
        "--vcd-ideal",
        action="store_true",
        dest="include_ideal_in_vcd",
        help="Include ideal output voltage in VCD traces.",
    )
    ap.add_argument(
        "--radix",
        choices=["dec", "hex", "bin", "all"],
        default="dec",
        help="Code display radix for terminal output.",
    )


def _add_analog_error_arguments(parsers: Iterable[argparse.ArgumentParser]) -> None:
    """Add common analog-path non-ideality arguments to DAC parsers."""
    for parser in parsers:
        parser.add_argument("--gain-err", type=float, default=0.0, help="Gain error fraction.")
        parser.add_argument("--vo-offset", type=float, default=0.0, help="Output offset in volts.")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog=_PACKAGE,
        description="DAC simulator for R-2R ladder and weighted-resistor converters.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    sub = parser.add_subparsers(dest="mode")

    r2r = sub.add_parser(
        "r2r",
        help="run an R-2R ladder DAC simulation",
        description="Run an R-2R ladder DAC simulation from CSV or JSON vectors.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    add_common(r2r)
    r2r.add_argument("--R", type=float, default=10_000.0, dest="R_ohm", help="Nominal R value in ohms.")
    r2r.add_argument("--sigma-r-pct", type=float, default=0.0, help="Standard deviation for R mismatch, percent.")
    r2r.add_argument("--sigma-2r-pct", type=float, default=0.0, help="Standard deviation for 2R mismatch, percent.")

    weighted = sub.add_parser(
        "weighted",
        help="run a binary weighted-resistor DAC simulation",
        description="Run a binary weighted-resistor DAC simulation from CSV or JSON vectors.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    add_common(weighted)
    weighted.add_argument(
        "--gain",
        type=float,
        default=1.0,
        dest="ro_over_r",
        help="Op-amp feedback/input resistance ratio for the weighted DAC model.",
    )
    weighted.add_argument("--res-sigma-pct", type=float, default=0.0, help="Resistor mismatch standard deviation, percent.")

    _add_analog_error_arguments((r2r, weighted))

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        description="Create conf.py, index.rst, api.rst, Makefile, _static/.gitkeep, and _templates/.gitkeep.",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _format_code(code: object, nbits: int, radix: str) -> str:
    """Format a DAC code in decimal, hexadecimal, binary, or all display modes."""
    try:
        value = int(code)
    except Exception:
        return str(code)

    width_hex = max(1, (int(nbits) + 3) // 4)
    value_masked = value & ((1 << int(nbits)) - 1)
    as_dec = str(value)
    as_hex = f"0x{value_masked:0{width_hex}X}"
    as_bin = f"0b{value_masked:0{int(nbits)}b}"

    if radix == "hex":
        return as_hex
    if radix == "bin":
        return as_bin
    if radix == "all":
        return f"{as_dec} / {as_hex} / {as_bin}"
    return as_dec


def _request_from_namespace(ns: argparse.Namespace) -> RunRequest:
    """Convert parsed CLI arguments into a :class:`RunRequest`."""
    common = dict(
        nbits=ns.nbits,
        vref=ns.vref,
        gain_err=ns.gain_err,
        vo_offset=ns.vo_offset,
        csv=ns.csv,
        jspec=ns.jspec,
        tupd=ns.tupd,
        in_dir=ns.in_dir,
        out_dir=ns.out_dir,
        out_csv=ns.out_csv,
        out_vcd=ns.out_vcd,
        out_vcd_all=ns.out_vcd_all,
        include_ideal_in_vcd=ns.include_ideal_in_vcd,
        radix=ns.radix,
    )

    if ns.mode == "r2r":
        return RunRequest(
            dac_type="r2r",
            R_ohm=ns.R_ohm,
            sigma_r_pct=ns.sigma_r_pct,
            sigma_2r_pct=ns.sigma_2r_pct,
            **common,
        )

    if ns.mode == "weighted":
        return RunRequest(
            dac_type="weighted",
            ro_over_r=ns.ro_over_r,
            res_sigma_pct=ns.res_sigma_pct,
            **common,
        )

    raise ValueError(f"Unsupported DAC mode: {ns.mode!r}")


def _run_dac(ns: argparse.Namespace) -> int:
    """Run one DAC simulation and print a friendly stream log."""
    req = _request_from_namespace(ns)
    result = run_app(req)

    for message in result.messages:
        print(message)

    for i, row in enumerate(result.rows):
        meta = row.meta
        code = _format_code(meta.get("code"), req.nbits, req.radix)
        vo_i = float(meta.get("vo_ideal", 0.0))
        vo_n = float(meta.get("vo_nonideal", 0.0))
        dv = float(meta.get("error", 0.0))
        print(f"[{i}] code={code} -> Vo_ideal={vo_i:.6g} V, Vo={vo_n:.6g} V, Δ={dv:+.6g} V")

    return 0


def _run_sphinx_skel(ns: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(ns.dest, force=ns.force)
    print(f"Sphinx skeleton ready: {ns.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {ns.dest / '_static' / '.gitkeep'}")
    print(f"  {ns.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the dacTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.mode == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.mode in {"r2r", "weighted"}:
        return _run_dac(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
